// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PlatformInfo - Public metadata for one registered plugin (admin UI). Maps 1:1 from [`plugin_core::PluginInfo`] (same field shape as before).
type PlatformInfo struct {
	Author string `json:"author"`
	Changelog []ChangelogEntry `json:"changelog"`
	ConfigFieldNames []string `json:"config_field_names"`
	ConfigFields []ConfigFieldInfo `json:"config_fields"`
	DisplayName string `json:"display_name"`
	Platform string `json:"platform"`
	Pricing PluginPricing `json:"pricing"`
	SupportedEntities []string `json:"supported_entities"`
	SupportsExport bool `json:"supports_export"`
	SupportsImport bool `json:"supports_import"`
	SupportsOauth bool `json:"supports_oauth"`
	Version string `json:"version"`
}
