// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// RegisterRequest - RegisterRequest struct
type RegisterRequest struct {
	CompanyName string `json:"company_name"`
	Email string `json:"email"`
	FirstName string `json:"first_name"`
	LastName string `json:"last_name"`
	Password string `json:"password"`
	PrivacyAccepted bool `json:"privacy_accepted"`
}
