// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// IncomeStatement - IncomeStatement struct
type IncomeStatement struct {
	ExpenseItems []PnLItem `json:"expense_items"`
	NetIncome string `json:"net_income"`
	RevenueItems []PnLItem `json:"revenue_items"`
	TotalExpenses string `json:"total_expenses"`
	TotalRevenue string `json:"total_revenue"`
}
