// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PackingVideoResponse - PackingVideoResponse struct
type PackingVideoResponse struct {
	Message string `json:"message"`
	RecordingUrl string `json:"recording_url,omitempty"`
	Success bool `json:"success"`
}
