// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GdprUsageEvent - GdprUsageEvent struct
type GdprUsageEvent struct {
	CreatedAt string `json:"createdAt"`
	EventType string `json:"eventType"`
	Id string `json:"id"`
	Quantity int32 `json:"quantity"`
	TenantId string `json:"tenantId"`
}
