// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PostingCategoryCreate - PostingCategoryCreate struct
type PostingCategoryCreate struct {
	AccountNumber string `json:"accountNumber,omitempty"`
	AccountNumberSkr03 string `json:"accountNumberSkr03,omitempty"`
	AccountNumberSkr04 string `json:"accountNumberSkr04,omitempty"`
	AccountNumberSkr49 string `json:"accountNumberSkr49,omitempty"`
	CategoryType PostingCategoryType `json:"categoryType"`
	CreatedAt string `json:"createdAt"`
	DefaultVatRate int32 `json:"defaultVatRate"`
	Description string `json:"description,omitempty"`
	EksCategory string `json:"eksCategory,omitempty"`
	EuVatLine int32 `json:"euVatLine,omitempty"`
	InputVatPercentage string `json:"inputVatPercentage"`
	IsActive bool `json:"isActive"`
	IsSystem bool `json:"isSystem"`
	Name string `json:"name"`
	SkrVersion string `json:"skrVersion"`
	UpdatedAt string `json:"updatedAt,omitempty"`
	UserModifiedSkr03 bool `json:"userModifiedSkr03"`
	UserModifiedSkr04 bool `json:"userModifiedSkr04"`
}
