// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PackingCompleteResponse - PackingCompleteResponse struct
type PackingCompleteResponse struct {
	Message string `json:"message"`
	NewState string `json:"new_state"`
	OrderNumber string `json:"order_number"`
	Success bool `json:"success"`
}
