// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GezReport - Berechnungsergebnis des Rundfunkbeitrags für ein Unternehmen.
type GezReport struct {
	BeitragsfreieKfz int64 `json:"beitragsfreie_kfz"`
	BeitragspflichtigeKfz int64 `json:"beitragspflichtige_kfz"`
	Betriebsstaetten []BetriebsstaettenDetail `json:"betriebsstaetten"`
	Hinweis string `json:"hinweis"`
	HotelzimmerBeitrag string `json:"hotelzimmer_beitrag"`
	JaehrlicherBeitrag string `json:"jaehrlicher_beitrag"`
	Jahr int32 `json:"jahr"`
	KfzBeitrag string `json:"kfz_beitrag"`
	MonatlicherBeitrag string `json:"monatlicher_beitrag"`
	VierteljaehrlicherBeitrag string `json:"vierteljaehrlicher_beitrag"`
}
