// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ContactTimelineResponse - Aggregated per-contact timeline.
type ContactTimelineResponse struct {
	ContactId string `json:"contactId"`
	Events []TimelineEvent `json:"events"`
}
