// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GatewayOAuthAuthorizeRequest - GatewayOAuthAuthorizeRequest struct
type GatewayOAuthAuthorizeRequest struct {
	GatewayType string `json:"gateway_type"`
	RedirectUri string `json:"redirect_uri"`
}
