// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OssDependency - OssDependency struct
type OssDependency struct {
	DependencyType string `json:"dependency_type"`
	License string `json:"license,omitempty"`
	Name string `json:"name"`
	Version string `json:"version"`
}
