// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ComplianceTraining - ComplianceTraining struct
type ComplianceTraining struct {
	Assignable bool `json:"assignable,omitempty"`
	Code string `json:"code,omitempty"`
	CreatedAt string `json:"createdAt,omitempty"`
	DeletedAt string `json:"deletedAt,omitempty"`
	Description string `json:"description,omitempty"`
	Id string `json:"id,omitempty"`
	PassScore int32 `json:"passScore,omitempty"`
	PluginPlatform string `json:"pluginPlatform,omitempty"`
	Source TrainingSource `json:"source,omitempty"`
	TenantId string `json:"tenantId,omitempty"`
	Title string `json:"title,omitempty"`
	UpdatedAt string `json:"updatedAt,omitempty"`
	ValidityMonths int32 `json:"validityMonths,omitempty"`
}
