// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GatewayOAuthCallbackRequest - GatewayOAuthCallbackRequest struct
type GatewayOAuthCallbackRequest struct {
	Code string `json:"code"`
	GatewayType string `json:"gateway_type"`
	RedirectUri string `json:"redirect_uri"`
	State string `json:"state"`
}
