// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// DeliveryDateCreate - DeliveryDateCreate struct
type DeliveryDateCreate struct {
	CustomerId string `json:"customerId,omitempty"`
	FulfilledDate string `json:"fulfilledDate,omitempty"`
	Note string `json:"note,omitempty"`
	OrderNumber string `json:"orderNumber"`
	OriginalDate string `json:"originalDate,omitempty"`
	ProductId string `json:"productId,omitempty"`
	PromisedDate string `json:"promisedDate"`
	Status DeliveryDateStatus `json:"status"`
}
