// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// LaborCostRow - LaborCostRow struct
type LaborCostRow struct {
	Cost string `json:"cost"`
	EmployeeId string `json:"employeeId,omitempty"`
	GroupKey string `json:"groupKey"`
	Hours string `json:"hours"`
	Name string `json:"name,omitempty"`
}
