// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// MarketplaceWebhookEvent - MarketplaceWebhookEvent struct
type MarketplaceWebhookEvent struct {
	ConnectionId string `json:"connectionId"`
	EventBody interface{} `json:"eventBody,omitempty"`
	EventType string `json:"eventType"`
	Headers interface{} `json:"headers,omitempty"`
	Platform string `json:"platform"`
	Processed bool `json:"processed,omitempty"`
	ProcessingError string `json:"processingError,omitempty"`
}
