// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// AnlageSKfzHinweis - AnlageSKfzHinweis struct
type AnlageSKfzHinweis struct {
	Bezeichnung string `json:"bezeichnung"`
	Kennzeichen string `json:"kennzeichen"`
	PrivatAnteilProzent string `json:"privat_anteil_prozent"`
}
