// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TimeEntryClockIn - TimeEntryClockIn struct
type TimeEntryClockIn struct {
	Notes string `json:"notes,omitempty"`
}
