// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// MyTrainingItem - MyTrainingItem struct
type MyTrainingItem struct {
	AssignmentId string `json:"assignmentId"`
	CertificateId string `json:"certificateId,omitempty"`
	Code string `json:"code"`
	Description string `json:"description,omitempty"`
	DueDate string `json:"dueDate,omitempty"`
	LastScore int32 `json:"lastScore,omitempty"`
	PassScore int32 `json:"passScore"`
	Passed bool `json:"passed,omitempty"`
	Status AssignmentStatus `json:"status"`
	Title string `json:"title"`
	TrainingId string `json:"trainingId"`
	ValidUntil string `json:"validUntil,omitempty"`
}
