// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CreateSubscriptionRequest - CreateSubscriptionRequest struct
type CreateSubscriptionRequest struct {
	EventType string `json:"event_type"`
	IsActive bool `json:"is_active,omitempty"`
	Name string `json:"name"`
	Secret string `json:"secret,omitempty"`
	Url string `json:"url"`
}
