// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// SupportTicket - SupportTicket struct
type SupportTicket struct {
	AssignedTo string `json:"assignedTo,omitempty"`
	ChannelId string `json:"channelId,omitempty"`
	ChannelType SupportChannelType `json:"channelType,omitempty"`
	ClosedAt string `json:"closedAt,omitempty"`
	CreatedAt string `json:"createdAt"`
	CustomerEmail string `json:"customerEmail,omitempty"`
	CustomerId string `json:"customerId,omitempty"`
	CustomerName string `json:"customerName,omitempty"`
	ExternalId string `json:"externalId,omitempty"`
	FirstMessageAt string `json:"firstMessageAt"`
	LastMessageAt string `json:"lastMessageAt"`
	LeadId string `json:"leadId,omitempty"`
	MessageCount int32 `json:"messageCount"`
	OrderRef string `json:"orderRef,omitempty"`
	Priority TicketPriority `json:"priority"`
	Resolution string `json:"resolution,omitempty"`
	Status SupportTicketStatus `json:"status"`
	Subject string `json:"subject"`
	Tags interface{} `json:"tags"`
	TenantId string `json:"tenantId"`
	UpdatedAt string `json:"updatedAt,omitempty"`
}
