// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// UpdatePermissionsPayload - UpdatePermissionsPayload struct
type UpdatePermissionsPayload struct {
	Permissions []string `json:"permissions"`
}
