// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// EmissionTarget - EmissionTarget struct
type EmissionTarget struct {
	BaseValue string `json:"baseValue"`
	BaseYear int32 `json:"baseYear"`
	Description string `json:"description"`
	Scope EmissionTargetScope `json:"scope"`
	TargetValue string `json:"targetValue"`
	TargetYear int32 `json:"targetYear"`
	UpdatedAt string `json:"updatedAt,omitempty"`
}
