// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GoBdExportResponse - GoBdExportResponse struct
type GoBdExportResponse struct {
	BookingCount int32 `json:"booking_count"`
	CsvContent string `json:"csv_content"`
	Filename string `json:"filename"`
}
