// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// QuotaOverview - QuotaOverview struct
type QuotaOverview struct {
	Features PlanFeatures `json:"features"`
	IsTrialing bool `json:"isTrialing"`
	Limits PlanLimits `json:"limits"`
	Metered []MeteredUsage `json:"metered"`
	Plan string `json:"plan"`
	PlanName string `json:"planName"`
	TrialEndsAt string `json:"trialEndsAt,omitempty"`
	Usage UsageSnapshot `json:"usage"`
}
