// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TargetProgress - TargetProgress struct
type TargetProgress struct {
	BaseValue float64 `json:"base_value"`
	BaseYear int32 `json:"base_year"`
	Description string `json:"description"`
	Id string `json:"id"`
	ProgressPct float64 `json:"progress_pct,omitempty"`
	Scope string `json:"scope"`
	TargetValue float64 `json:"target_value"`
	TargetYear int32 `json:"target_year"`
}
