// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PosTable - A physical table at a restaurant/cafe POS. `current_order_number` links the open order occupying the table; `None` means free.
type PosTable struct {
	CurrentOrderNumber string `json:"currentOrderNumber,omitempty"`
	Name string `json:"name"`
	Status PosTableStatus `json:"status,omitempty"`
}
