// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// LeadUpdate - LeadUpdate struct
type LeadUpdate struct {
	Company string `json:"company,omitempty"`
	ConvertedAt string `json:"convertedAt,omitempty"`
	CreatedAt string `json:"createdAt,omitempty"`
	Email string `json:"email,omitempty"`
	FirstContactAt string `json:"firstContactAt,omitempty"`
	Name string `json:"name,omitempty"`
	Notes string `json:"notes,omitempty"`
	Phone string `json:"phone,omitempty"`
	Score int32 `json:"score,omitempty"`
	Source string `json:"source,omitempty"`
	Status LeadStatus `json:"status,omitempty"`
	Tags interface{} `json:"tags,omitempty"`
	TenantId string `json:"tenantId,omitempty"`
	UpdatedAt string `json:"updatedAt,omitempty"`
}
