// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// SepaDirectDebitResponse - SepaDirectDebitResponse struct
type SepaDirectDebitResponse struct {
	ContentType string `json:"content_type"`
	Filename string `json:"filename"`
	XmlContent string `json:"xml_content"`
}
