// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PeppolResponse - PeppolResponse struct
type PeppolResponse struct {
	Content string `json:"content"`
	ContentType string `json:"content_type"`
	Filename string `json:"filename"`
}
