// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// JahresUstErgebnis - JahresUstErgebnis struct
type JahresUstErgebnis struct {
	Bis string `json:"bis"`
	GespeichertePerioden int32 `json:"gespeicherte_perioden"`
	HatIgTransaktionen bool `json:"hat_ig_transaktionen"`
	IstKleinunternehmer bool `json:"ist_kleinunternehmer"`
	Jahr int32 `json:"jahr"`
	Kz41 string `json:"kz_41"`
	Kz43 string `json:"kz_43"`
	Kz46 string `json:"kz_46"`
	Kz47 string `json:"kz_47"`
	Kz48 string `json:"kz_48"`
	Kz61 string `json:"kz_61"`
	Kz66 string `json:"kz_66"`
	Kz67 string `json:"kz_67"`
	Kz81 string `json:"kz_81"`
	Kz83 string `json:"kz_83"`
	Kz84 string `json:"kz_84"`
	Kz85 string `json:"kz_85"`
	Kz86 string `json:"kz_86"`
	Kz88 string `json:"kz_88"`
	Kz89 string `json:"kz_89"`
	Kz93 string `json:"kz_93"`
	Restschuld string `json:"restschuld"`
	SummeVorauszahlungen string `json:"summe_vorauszahlungen"`
	Von string `json:"von"`
	Zahllast string `json:"zahllast"`
}
