// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// AutomationDto - AutomationDto struct
type AutomationDto struct {
	AutomationKey string `json:"automationKey"`
	Config interface{} `json:"config"`
	DefaultDay int32 `json:"defaultDay,omitempty"`
	Description string `json:"description"`
	Enabled bool `json:"enabled"`
	Kind string `json:"kind"`
	LastRunAt string `json:"lastRunAt,omitempty"`
	NextRunAt string `json:"nextRunAt,omitempty"`
	ScheduleKind string `json:"scheduleKind"`
}
