// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// UpdateAutomation - UpdateAutomation struct
type UpdateAutomation struct {
	Config interface{} `json:"config,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
}
