// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// AllocatePaymentRequest - AllocatePaymentRequest struct
type AllocatePaymentRequest struct {
	Amount float64 `json:"amount"`
	InvoiceId string `json:"invoice_id"`
	PaymentId string `json:"payment_id"`
}
