// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// EuerZeileDetail - EuerZeileDetail struct
type EuerZeileDetail struct {
	Abschnitt string `json:"abschnitt"`
	BetragGesamt string `json:"betrag_gesamt"`
	Bezeichnung string `json:"bezeichnung"`
	Kategorien []EuerKatSumme `json:"kategorien"`
	Zeile int32 `json:"zeile"`
}
