// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// DownPaymentInvoice - DownPaymentInvoice struct
type DownPaymentInvoice struct {
	ContactId string `json:"contact_id,omitempty"`
	ContactName string `json:"contact_name,omitempty"`
	CreatedAt string `json:"created_at"`
	Currency string `json:"currency"`
	Id string `json:"id"`
	Notes string `json:"notes,omitempty"`
	PaidAmount string `json:"paid_amount"`
	TotalAmount string `json:"total_amount"`
	VoucherDate string `json:"voucher_date"`
	VoucherNumber string `json:"voucher_number,omitempty"`
	VoucherStatus string `json:"voucher_status"`
}
