// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// DeliveryDateStatusUpdate - DeliveryDateStatusUpdate struct
type DeliveryDateStatusUpdate struct {
	Status string `json:"status"`
}
