// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// InstituteDeadlines - InstituteDeadlines struct
type InstituteDeadlines struct {
	AbschlusspruefungMonths int32 `json:"abschlusspruefungMonths,omitempty"`
	JahresabschlussBafinMonths int32 `json:"jahresabschlussBafinMonths,omitempty"`
	OffenlegungMonths int32 `json:"offenlegungMonths"`
}
