// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GdprUser - GdprUser struct
type GdprUser struct {
	CreatedAt string `json:"createdAt"`
	Email string `json:"email"`
	Id string `json:"id"`
	Name string `json:"name"`
}
