// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ApiResponseVecPlan - ApiResponseVecPlan struct
type ApiResponseVecPlan struct {
	Data []ApiResponseVecPlanDataInner `json:"data,omitempty"`
	Error string `json:"error,omitempty"`
	Message string `json:"message,omitempty"`
	Success bool `json:"success"`
}
