// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// HrTrainingOverview - HrTrainingOverview struct
type HrTrainingOverview struct {
	AssignedCount int64 `json:"assignedCount"`
	Code string `json:"code"`
	CompletedCount int64 `json:"completedCount"`
	OverdueCount int64 `json:"overdueCount"`
	Title string `json:"title"`
	TrainingId string `json:"trainingId"`
}
