// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ComplianceEntry - ComplianceEntry struct
type ComplianceEntry struct {
	Description string `json:"description"`
	Module string `json:"module"`
	Regulations []string `json:"regulations"`
}
