// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TimeEntryDto - API shape returned to the frontend (matches `frontend/src/types/time-entry.ts`).
type TimeEntryDto struct {
	ClockIn string `json:"clock_in,omitempty"`
	ClockOut string `json:"clock_out,omitempty"`
	CreatedAt string `json:"created_at"`
	Date string `json:"date"`
	EmployeeId string `json:"employee_id"`
	Hours string `json:"hours,omitempty"`
	Notes string `json:"notes,omitempty"`
	TimeEntryId string `json:"time_entry_id"`
}
