// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// DeliveryAppointmentStatus - Delivery appointment status.
type DeliveryAppointmentStatus struct {
}
