// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TrainingContent - TrainingContent struct
type TrainingContent struct {
	Code string `json:"code"`
	Contact ContactInfo `json:"contact"`
	PassScore int32 `json:"passScore"`
	Quiz []QuizQuestion `json:"quiz"`
	Sections []Section `json:"sections"`
	Title string `json:"title"`
	TitleEn string `json:"titleEn"`
}
