// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// MethodSuitability - MethodSuitability struct
type MethodSuitability struct {
	Carrier string `json:"carrier"`
	Rate ShippingRate `json:"rate,omitempty"`
	Reasons []string `json:"reasons"`
	Service string `json:"service"`
	Suitable bool `json:"suitable"`
}
