// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PayrollCreatePayload - PayrollCreatePayload struct
type PayrollCreatePayload struct {
	EmployeeIds []string `json:"employee_ids"`
	ExtraPayments []ExtraPayment `json:"extra_payments,omitempty"`
	Month int32 `json:"month"`
	Year int32 `json:"year"`
}
