// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ProductCategoryUpdate - ProductCategoryUpdate struct
type ProductCategoryUpdate struct {
	Description string `json:"description,omitempty"`
	Name string `json:"name,omitempty"`
	ParentCategoryId string `json:"parentCategoryId,omitempty"`
	SortOrder int32 `json:"sortOrder,omitempty"`
}
