// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// BwaSummary - BwaSummary struct
type BwaSummary struct {
	GrossProfit string `json:"gross_profit"`
	NetProfit string `json:"net_profit"`
	OpenInvoicesCount int64 `json:"open_invoices_count"`
	OpenInvoicesTotal string `json:"open_invoices_total"`
	OverdueInvoicesCount int64 `json:"overdue_invoices_count"`
	OverdueInvoicesTotal string `json:"overdue_invoices_total"`
	ProfitMargin float64 `json:"profit_margin"`
}
