// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// AppointmentStatusUpdate - AppointmentStatusUpdate struct
type AppointmentStatusUpdate struct {
	Status string `json:"status"`
}
