// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PostingCategory - PostingCategory struct
type PostingCategory struct {
	AccountNumber string `json:"account_number,omitempty"`
	AccountNumberSkr03 string `json:"account_number_skr03,omitempty"`
	AccountNumberSkr04 string `json:"account_number_skr04,omitempty"`
	AccountNumberSkr49 string `json:"account_number_skr49,omitempty"`
	CategoryId string `json:"category_id"`
	DefaultVatRate int32 `json:"default_vat_rate"`
	Description string `json:"description,omitempty"`
	EksCategory string `json:"eks_category,omitempty"`
	IsActive bool `json:"is_active"`
	IsSystem bool `json:"is_system"`
	Name string `json:"name"`
	SkrVersion string `json:"skr_version"`
	Type string `json:"type"`
}
