// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TimeEntryClockOut - TimeEntryClockOut struct
type TimeEntryClockOut struct {
	ClockOut string `json:"clock_out"`
	Hours string `json:"hours,omitempty"`
}
