// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// InvoiceMatchRequest - InvoiceMatchRequest struct
type InvoiceMatchRequest struct {
	SupplierInvoiceId string `json:"supplier_invoice_id"`
}
