// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ReturnLogisticsQueueItem - One open return awaiting warehouse processing (inbound queue).
type ReturnLogisticsQueueItem struct {
	AgeDays int64 `json:"ageDays"`
	CreatedAt string `json:"createdAt"`
	CustomerName string `json:"customerName,omitempty"`
	LineItems interface{} `json:"lineItems"`
	OrderNumber string `json:"orderNumber,omitempty"`
	ReturnNumber string `json:"returnNumber"`
	ReturnOrderId string `json:"returnOrderId"`
	Status string `json:"status"`
	WarehouseId string `json:"warehouseId,omitempty"`
}
