// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OAuthAuthorizeResponse - OAuthAuthorizeResponse struct
type OAuthAuthorizeResponse struct {
	AuthorizationUrl string `json:"authorization_url"`
	State string `json:"state"`
}
