// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Lead - Lead struct
type Lead struct {
	Company string `json:"company,omitempty"`
	ConvertedAt string `json:"convertedAt,omitempty"`
	CreatedAt string `json:"createdAt"`
	Email string `json:"email,omitempty"`
	FirstContactAt string `json:"firstContactAt"`
	Name string `json:"name"`
	Notes string `json:"notes,omitempty"`
	Phone string `json:"phone,omitempty"`
	Score int32 `json:"score"`
	Source string `json:"source"`
	Status LeadStatus `json:"status"`
	Tags interface{} `json:"tags"`
	TenantId string `json:"tenantId"`
	UpdatedAt string `json:"updatedAt,omitempty"`
}
