// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PayrollRunApi - PayrollRunApi struct
type PayrollRunApi struct {
	ApprovedAt string `json:"approved_at,omitempty"`
	ApprovedBy string `json:"approved_by,omitempty"`
	CreatedAt string `json:"created_at"`
	Entries []PayrollEntryApi `json:"entries"`
	Month int32 `json:"month"`
	PaymentDate string `json:"payment_date,omitempty"`
	PeriodLabel string `json:"period_label"`
	RunId string `json:"run_id"`
	Status PayrollRunStatus `json:"status"`
	TenantId string `json:"tenant_id"`
	TotalEmployeeCount int32 `json:"total_employee_count"`
	TotalEmployerCost string `json:"total_employer_cost"`
	TotalGross string `json:"total_gross"`
	TotalNet string `json:"total_net"`
	TotalSocialSecurity string `json:"total_social_security"`
	TotalTaxes string `json:"total_taxes"`
	UpdatedAt string `json:"updated_at,omitempty"`
	Year int32 `json:"year"`
}
