// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Betriebsstaette - Eine Betriebsstätte mit der Anzahl der sozialversicherungspflichtig Beschäftigten (Jahresdurchschnitt des Vorjahres).
type Betriebsstaette struct {
	Beschaefigte int64 `json:"beschaefigte"`
	Name string `json:"name"`
}
