// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Package - Package struct
type Package struct {
	Description string `json:"description,omitempty"`
	HeightCm float64 `json:"height_cm,omitempty"`
	LengthCm float64 `json:"length_cm,omitempty"`
	Reference string `json:"reference,omitempty"`
	WeightKg float64 `json:"weight_kg"`
	WidthCm float64 `json:"width_cm,omitempty"`
}
