// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GdprNotification - GdprNotification struct
type GdprNotification struct {
	CreatedAt string `json:"createdAt"`
	Id string `json:"id"`
	IsRead bool `json:"isRead"`
	Message string `json:"message,omitempty"`
	TenantId string `json:"tenantId"`
	Title string `json:"title"`
}
