// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PurchaseOrderUpdate - PurchaseOrderUpdate struct
type PurchaseOrderUpdate struct {
	Currency string `json:"currency,omitempty"`
	DeliveryAddress interface{} `json:"deliveryAddress,omitempty"`
	ExpectedDeliveryDate string `json:"expectedDeliveryDate,omitempty"`
	LineItems interface{} `json:"lineItems,omitempty"`
	Notes string `json:"notes,omitempty"`
	OrderDate string `json:"orderDate,omitempty"`
	PoNumber string `json:"poNumber,omitempty"`
	Status PurchaseOrderStatus `json:"status,omitempty"`
	SupplierContactId string `json:"supplierContactId,omitempty"`
	SupplierName string `json:"supplierName,omitempty"`
	TotalGrossAmount string `json:"totalGrossAmount,omitempty"`
	TotalNetAmount string `json:"totalNetAmount,omitempty"`
}
