// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TeamCreate - TeamCreate struct
type TeamCreate struct {
	Description string `json:"description,omitempty"`
	Name string `json:"name"`
	ParentTeamId string `json:"parentTeamId,omitempty"`
}
