// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ImportStartResponse - ImportStartResponse struct
type ImportStartResponse struct {
	JobId string `json:"job_id"`
}
