// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ApiResponseGdprExport - ApiResponseGdprExport struct
type ApiResponseGdprExport struct {
	Data ApiResponseGdprExportData `json:"data,omitempty"`
	Error string `json:"error,omitempty"`
	Message string `json:"message,omitempty"`
	Success bool `json:"success"`
}
