// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// SilentPartnerCreate - SilentPartnerCreate struct
type SilentPartnerCreate struct {
	ContractDate string `json:"contractDate,omitempty"`
	Einlage string `json:"einlage,omitempty"`
	GewinnquotePct string `json:"gewinnquotePct,omitempty"`
	Gewinnvortrag string `json:"gewinnvortrag,omitempty"`
	InstrumentType InstrumentType `json:"instrumentType"`
	KestPflichtig bool `json:"kestPflichtig,omitempty"`
	Name string `json:"name,omitempty"`
	Notes string `json:"notes,omitempty"`
	VerlustVerrechnungskonto string `json:"verlustVerrechnungskonto,omitempty"`
	Verlustbeteiligung bool `json:"verlustbeteiligung,omitempty"`
}
