// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ParticipationUpdate - ParticipationUpdate struct
type ParticipationUpdate struct {
	AcquiredAt string `json:"acquiredAt,omitempty"`
	BoardAppointment bool `json:"boardAppointment,omitempty"`
	CompanyName string `json:"companyName,omitempty"`
	ControlAgreement bool `json:"controlAgreement,omitempty"`
	LegalForm string `json:"legalForm,omitempty"`
	OwnershipPct string `json:"ownershipPct,omitempty"`
	PurposeVehicle bool `json:"purposeVehicle,omitempty"`
	VotingMajority bool `json:"votingMajority,omitempty"`
}
