// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ProductAttributeCreate - ProductAttributeCreate struct
type ProductAttributeCreate struct {
	IsFilterable bool `json:"isFilterable,omitempty"`
	Name string `json:"name"`
	Position int32 `json:"position,omitempty"`
	ProductId string `json:"productId"`
	Unit string `json:"unit,omitempty"`
	Value string `json:"value"`
}
