// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// SupplierInvoiceUpdate - SupplierInvoiceUpdate struct
type SupplierInvoiceUpdate struct {
	Currency string `json:"currency,omitempty"`
	GoodsReceiptId string `json:"goodsReceiptId,omitempty"`
	InvoiceDate string `json:"invoiceDate,omitempty"`
	InvoiceNumber string `json:"invoiceNumber,omitempty"`
	LineItems interface{} `json:"lineItems,omitempty"`
	Notes string `json:"notes,omitempty"`
	PurchaseOrderId string `json:"purchaseOrderId,omitempty"`
	Status SupplierInvoiceStatus `json:"status,omitempty"`
	SupplierContactId string `json:"supplierContactId,omitempty"`
	SupplierName string `json:"supplierName,omitempty"`
	TotalGrossAmount string `json:"totalGrossAmount,omitempty"`
	TotalNetAmount string `json:"totalNetAmount,omitempty"`
}
