// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GdprBillingInfo - GdprBillingInfo struct
type GdprBillingInfo struct {
	CurrentPeriodEnd string `json:"currentPeriodEnd,omitempty"`
	CurrentPeriodStart string `json:"currentPeriodStart,omitempty"`
	Plan string `json:"plan,omitempty"`
	Status string `json:"status,omitempty"`
	TenantId string `json:"tenantId"`
}
