// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// DeliveryNoteCreate - DeliveryNoteCreate struct
type DeliveryNoteCreate struct {
	Address interface{} `json:"address,omitempty"`
	ContactId string `json:"contactId,omitempty"`
	ContactName string `json:"contactName,omitempty"`
	Currency string `json:"currency"`
	DeliveryDate string `json:"deliveryDate,omitempty"`
	DeliveryNoteNumber string `json:"deliveryNoteNumber,omitempty"`
	Files interface{} `json:"files,omitempty"`
	Introduction string `json:"introduction,omitempty"`
	LineItems interface{} `json:"lineItems,omitempty"`
	PrecedingSalesVoucherId string `json:"precedingSalesVoucherId,omitempty"`
	PrecedingSalesVoucherType PrecedingSalesVoucherType `json:"precedingSalesVoucherType,omitempty"`
	Remark string `json:"remark,omitempty"`
	ShippingDate string `json:"shippingDate,omitempty"`
	ShippingMethod string `json:"shippingMethod,omitempty"`
	Title string `json:"title,omitempty"`
	VoucherDate string `json:"voucherDate"`
	VoucherStatus VoucherStatus `json:"voucherStatus"`
}
