// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GuVItem - GuVItem struct
type GuVItem struct {
	Account string `json:"account"`
	Amount string `json:"amount"`
	Name string `json:"name"`
}
