// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// SalesVolumeReport - SalesVolumeReport struct
type SalesVolumeReport struct {
	GrandTotal string `json:"grand_total"`
	Items []SalesVolumeItem `json:"items"`
	TotalCount int64 `json:"total_count"`
}
