// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PayGapExportResponse - PayGapExportResponse struct
type PayGapExportResponse struct {
	CsvContent string `json:"csv_content"`
	Filename string `json:"filename"`
}
