// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// KontoItem - KontoItem struct
type KontoItem struct {
	Anfangsbestand string `json:"anfangsbestand"`
	HabenUmsatz string `json:"haben_umsatz"`
	Konto string `json:"konto"`
	Name string `json:"name"`
	Saldo string `json:"saldo"`
	SollUmsatz string `json:"soll_umsatz"`
}
