// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GdprActivity - GdprActivity struct
type GdprActivity struct {
	Action string `json:"action"`
	CreatedAt string `json:"createdAt"`
	Description string `json:"description,omitempty"`
	Id string `json:"id"`
	TenantId string `json:"tenantId"`
}
