// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// UpdateChannelDto - UpdateChannelDto struct
type UpdateChannelDto struct {
	Config interface{} `json:"config,omitempty"`
	IsActive bool `json:"is_active,omitempty"`
	Name string `json:"name,omitempty"`
}
