// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ConfigFieldInfo - Owned, API-safe copy of a [`ConfigField`] for DTOs / OpenAPI ([`ConfigField`] borrows `&'static str`, which cannot round-trip `Deserialize`).
type ConfigFieldInfo struct {
	Kind ConfigFieldKind `json:"kind"`
	Label string `json:"label"`
	Name string `json:"name"`
	Placeholder string `json:"placeholder,omitempty"`
	Required bool `json:"required"`
}
