// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// DataQuality - DataQuality struct
type DataQuality struct {
	ActivityLines int32 `json:"activity_lines"`
	ActivitySharePct float64 `json:"activity_share_pct"`
	SpendLines int32 `json:"spend_lines"`
}
