// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TrackedShipment - TrackedShipment struct
type TrackedShipment struct {
	Carrier string `json:"carrier"`
	Events []TrackingEvent `json:"events"`
	LabelUrl string `json:"label_url,omitempty"`
	Status string `json:"status"`
	TrackingNumber string `json:"tracking_number,omitempty"`
	TrackingUrl string `json:"tracking_url,omitempty"`
}
