// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ProposedAssignment - ProposedAssignment struct
type ProposedAssignment struct {
	AmountPaid string `json:"amount_paid"`
	Confidence float64 `json:"confidence"`
	CustomerId string `json:"customer_id,omitempty"`
	InvoiceId string `json:"invoice_id"`
	InvoiceNumber string `json:"invoice_number"`
	OpenAmount string `json:"open_amount"`
	PaymentDate string `json:"payment_date"`
	PaymentId string `json:"payment_id"`
	Reason string `json:"reason"`
	Reference string `json:"reference,omitempty"`
}
