// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PayrollEntryApi - PayrollEntryApi struct
type PayrollEntryApi struct {
	AvEmployee string `json:"av_employee"`
	AvEmployer string `json:"av_employer"`
	ChurchTaxAmount string `json:"church_tax_amount"`
	Employee Employee `json:"employee,omitempty"`
	EmployeeId string `json:"employee_id"`
	EntryId string `json:"entry_id"`
	ExtraPaymentReason string `json:"extra_payment_reason,omitempty"`
	ExtraPayments string `json:"extra_payments"`
	GrossSalary string `json:"gross_salary"`
	KvEmployee string `json:"kv_employee"`
	KvEmployer string `json:"kv_employer"`
	Lohnsteuer string `json:"lohnsteuer"`
	NetSalary string `json:"net_salary"`
	Notes string `json:"notes,omitempty"`
	PvEmployee string `json:"pv_employee"`
	PvEmployer string `json:"pv_employer"`
	RunId string `json:"run_id"`
	RvEmployee string `json:"rv_employee"`
	RvEmployer string `json:"rv_employer"`
	SickDays int32 `json:"sick_days"`
	Soli string `json:"soli"`
	Status PayrollRunStatus `json:"status"`
	TotalDeductions string `json:"total_deductions"`
	TotalEmployerCost string `json:"total_employer_cost"`
	VacationDaysUsed int32 `json:"vacation_days_used"`
}
