// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// MarketplaceConnection - MarketplaceConnection struct
type MarketplaceConnection struct {
	Config interface{} `json:"config"`
	ConnectionId string `json:"connection_id"`
	ConnectorType ConnectorType `json:"connector_type"`
	CreatedAt string `json:"created_at"`
	IsActive bool `json:"is_active"`
	Label string `json:"label"`
	LastSyncAt string `json:"last_sync_at,omitempty"`
	Platform string `json:"platform"`
	PlatformUserId string `json:"platform_user_id,omitempty"`
	Scopes string `json:"scopes,omitempty"`
	ShopDomain string `json:"shop_domain,omitempty"`
	ShopName string `json:"shop_name,omitempty"`
	SyncStatus string `json:"sync_status,omitempty"`
	TenantId string `json:"tenant_id"`
	UpdatedAt string `json:"updated_at,omitempty"`
}
