// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OcrTextRequest - OcrTextRequest struct
type OcrTextRequest struct {
	OcrText string `json:"ocrText,omitempty"`
}
