// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// EuerKatSumme - EuerKatSumme struct
type EuerKatSumme struct {
	Betrag string `json:"betrag"`
	Name string `json:"name"`
}
