// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ProductAttributeUpdate - ProductAttributeUpdate struct
type ProductAttributeUpdate struct {
	IsFilterable bool `json:"isFilterable,omitempty"`
	Name string `json:"name,omitempty"`
	Position int32 `json:"position,omitempty"`
	ProductId string `json:"productId,omitempty"`
	Unit string `json:"unit,omitempty"`
	Value string `json:"value,omitempty"`
}
