// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// EmitEventRequest - EmitEventRequest struct
type EmitEventRequest struct {
	EventType string `json:"event_type"`
	Payload interface{} `json:"payload,omitempty"`
}
