// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ConfigFieldKindOneOf4 - ConfigFieldKindOneOf4 struct
type ConfigFieldKindOneOf4 struct {
	Type string `json:"type"`
}
