// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ProformaInvoiceUpdate - ProformaInvoiceUpdate struct
type ProformaInvoiceUpdate struct {
	ConvertedAt string `json:"convertedAt,omitempty"`
	ConvertedToInvoiceId string `json:"convertedToInvoiceId,omitempty"`
	Currency CurrencyCode `json:"currency,omitempty"`
	CustomerId string `json:"customerId,omitempty"`
	CustomerSnapshot interface{} `json:"customerSnapshot,omitempty"`
	IssueDate string `json:"issueDate,omitempty"`
	LineItems interface{} `json:"lineItems,omitempty"`
	Notes string `json:"notes,omitempty"`
	OrderNumber string `json:"orderNumber,omitempty"`
	PaymentDueDate string `json:"paymentDueDate,omitempty"`
	QuotationId string `json:"quotationId,omitempty"`
	Status ProformaInvoiceStatus `json:"status,omitempty"`
	Subtotal string `json:"subtotal,omitempty"`
	TotalAmount string `json:"totalAmount,omitempty"`
	TotalTax string `json:"totalTax,omitempty"`
}
