// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// UpdateSyncDirectionRequest - UpdateSyncDirectionRequest struct
type UpdateSyncDirectionRequest struct {
	Directions map[string]string `json:"directions"`
}
