// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// SupplierConditionUpdate - SupplierConditionUpdate struct
type SupplierConditionUpdate struct {
	Currency string `json:"currency,omitempty"`
	DeliveryTerms string `json:"deliveryTerms,omitempty"`
	EarlyPaymentDiscountPercent string `json:"earlyPaymentDiscountPercent,omitempty"`
	IsDefault bool `json:"isDefault,omitempty"`
	MinimumOrderValue string `json:"minimumOrderValue,omitempty"`
	Notes string `json:"notes,omitempty"`
	PaymentDueDays int32 `json:"paymentDueDays,omitempty"`
	PaymentTerms string `json:"paymentTerms,omitempty"`
	SupplierContactId string `json:"supplierContactId,omitempty"`
	SupplierName string `json:"supplierName,omitempty"`
	VolumeDiscountTiers interface{} `json:"volumeDiscountTiers,omitempty"`
}
