// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// SyncSummary - Result of a sync/export run — what the app reports back to the admin UI.
type SyncSummary struct {
	ErrorMessage string `json:"error_message,omitempty"`
	ItemsFailed int32 `json:"items_failed,omitempty"`
	ItemsSynced int32 `json:"items_synced,omitempty"`
}
