// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PrintDeliveryNoteResponse - PrintDeliveryNoteResponse struct
type PrintDeliveryNoteResponse struct {
	Message string `json:"message"`
	PdfUrl string `json:"pdf_url,omitempty"`
	Success bool `json:"success"`
}
