// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// StockMovement - StockMovement struct
type StockMovement struct {
	Delta int64 `json:"delta"`
	MovementType MovementType `json:"movementType"`
	ProductId string `json:"productId"`
	Quantity int64 `json:"quantity"`
	Reason string `json:"reason,omitempty"`
	ReferenceId string `json:"referenceId,omitempty"`
	ReferenceType ReferenceType `json:"referenceType,omitempty"`
	WarehouseId string `json:"warehouseId"`
}
