// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ShipmentStatusUpdate - ShipmentStatusUpdate struct
type ShipmentStatusUpdate struct {
	DeliveredAt string `json:"delivered_at,omitempty"`
	SignedBy string `json:"signed_by,omitempty"`
	Status string `json:"status"`
	TrackingNumber string `json:"tracking_number,omitempty"`
}
