// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// StilleExportResponse - StilleExportResponse struct
type StilleExportResponse struct {
	CsvContent string `json:"csv_content"`
	Filename string `json:"filename"`
}
