// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// XRechnungResponse - XRechnungResponse struct
type XRechnungResponse struct {
	Content string `json:"content"`
	ContentType string `json:"content_type"`
	Filename string `json:"filename"`
}
