// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ShippingThresholdCreate - ShippingThresholdCreate struct
type ShippingThresholdCreate struct {
	IsActive bool `json:"isActive,omitempty"`
	MaxSellable int64 `json:"maxSellable,omitempty"`
	Name string `json:"name"`
	Notes string `json:"notes,omitempty"`
	ProductId string `json:"productId,omitempty"`
	ReserveStock int64 `json:"reserveStock,omitempty"`
	WarehouseId string `json:"warehouseId,omitempty"`
}
