// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GoodsReceipt - GoodsReceipt struct
type GoodsReceipt struct {
	GrNumber string `json:"grNumber"`
	LineItems interface{} `json:"lineItems"`
	Notes string `json:"notes,omitempty"`
	PurchaseOrderId string `json:"purchaseOrderId,omitempty"`
	ReceiptDate string `json:"receiptDate"`
	SupplierContactId string `json:"supplierContactId,omitempty"`
	SupplierName string `json:"supplierName,omitempty"`
	WarehouseId string `json:"warehouseId"`
}
