// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// FristenErgebnis - FristenErgebnis struct
type FristenErgebnis struct {
	Anzahl int32 `json:"anzahl"`
	Fristen []FristEintrag `json:"fristen"`
}
