// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Team - Team struct
type Team struct {
	CreatedAt string `json:"created_at"`
	Description string `json:"description,omitempty"`
	Id string `json:"id"`
	Name string `json:"name"`
	ParentTeamId string `json:"parent_team_id,omitempty"`
	TenantId string `json:"tenant_id"`
	UpdatedAt string `json:"updated_at"`
}
