// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PluginErrorOneOf2 - PluginErrorOneOf2 struct
type PluginErrorOneOf2 struct {
	Unauthorized []map[string]interface{} `json:"Unauthorized"`
}
