// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// WebhookSubscription - WebhookSubscription struct
type WebhookSubscription struct {
	EventType string `json:"eventType"`
	IsActive bool `json:"isActive,omitempty"`
	Name string `json:"name"`
	Secret string `json:"secret"`
	Url string `json:"url"`
}
