// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// JobTitleGap - JobTitleGap struct
type JobTitleGap struct {
	EmployeeCount int32 `json:"employee_count"`
	FemaleMeanHourly string `json:"female_mean_hourly"`
	JobTitle string `json:"job_title"`
	MaleMeanHourly string `json:"male_mean_hourly"`
	MeanGapPct float64 `json:"mean_gap_pct"`
	MedianGapPct float64 `json:"median_gap_pct"`
}
