// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PriceTierCreate - PriceTierCreate struct
type PriceTierCreate struct {
	CustomerGroupId string `json:"customerGroupId,omitempty"`
	MinQuantity int64 `json:"minQuantity,omitempty"`
	ProductId string `json:"productId"`
	UnitPrice string `json:"unitPrice"`
}
