// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// AiWorkerConfig - AiWorkerConfig struct
type AiWorkerConfig struct {
	AutoReply bool `json:"auto_reply"`
	CreatedAt string `json:"created_at"`
	Id string `json:"id"`
	IsActive bool `json:"is_active"`
	MaxToolCalls int32 `json:"max_tool_calls"`
	Model string `json:"model"`
	Name string `json:"name"`
	Provider string `json:"provider"`
	SystemPrompt string `json:"system_prompt"`
	TenantId string `json:"tenant_id"`
	TriggerOn []string `json:"trigger_on"`
	UpdatedAt string `json:"updated_at,omitempty"`
}
