// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// InvoicePdfUrlResponse - InvoicePdfUrlResponse struct
type InvoicePdfUrlResponse struct {
	Url string `json:"url"`
}
