// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomerGroupCreate - CustomerGroupCreate struct
type CustomerGroupCreate struct {
	Description string `json:"description,omitempty"`
	MemberIds []string `json:"memberIds,omitempty"`
	MembershipFilter string `json:"membershipFilter,omitempty"`
	Name string `json:"name"`
}
