// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ServiceJobCreate - ServiceJobCreate struct
type ServiceJobCreate struct {
	Address string `json:"address,omitempty"`
	CustomerEmail string `json:"customerEmail,omitempty"`
	CustomerId string `json:"customerId,omitempty"`
	CustomerName string `json:"customerName,omitempty"`
	CustomerPhone string `json:"customerPhone,omitempty"`
	Description string `json:"description,omitempty"`
	EstimatedDurationMinutes int32 `json:"estimatedDurationMinutes,omitempty"`
	Lat float64 `json:"lat,omitempty"`
	Lng float64 `json:"lng,omitempty"`
	Notes string `json:"notes,omitempty"`
	Status ServiceJobStatus `json:"status,omitempty"`
}
