// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// EmissionsReport - EmissionsReport struct
type EmissionsReport struct {
	ByCategory []CategoryTotal `json:"by_category"`
	ByScope []ScopeTotal `json:"by_scope"`
	ByYear []YearTotal `json:"by_year"`
	DataQuality DataQuality `json:"data_quality"`
	IntensityPerEmployee float64 `json:"intensity_per_employee,omitempty"`
	IntensityPerRevenueMio float64 `json:"intensity_per_revenue_mio,omitempty"`
	NetRevenue float64 `json:"net_revenue,omitempty"`
	SpendBasedEstimateTco2e float64 `json:"spend_based_estimate_tco2e,omitempty"`
	Targets []TargetProgress `json:"targets"`
	TotalTco2e string `json:"total_tco2e"`
}
