// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// UstvaErgebnis - UstvaErgebnis struct
type UstvaErgebnis struct {
	Bis string `json:"bis"`
	Hinweis string `json:"hinweis,omitempty"`
	IstKleinunternehmer bool `json:"ist_kleinunternehmer"`
	Kz41 string `json:"kz_41"`
	Kz43 string `json:"kz_43"`
	Kz46 string `json:"kz_46"`
	Kz47 string `json:"kz_47"`
	Kz61 string `json:"kz_61"`
	Kz66 string `json:"kz_66"`
	Kz67 string `json:"kz_67"`
	Kz81 string `json:"kz_81"`
	Kz83 string `json:"kz_83"`
	Kz84 string `json:"kz_84"`
	Kz85 string `json:"kz_85"`
	Kz86 string `json:"kz_86"`
	Kz88 string `json:"kz_88"`
	Kz89 string `json:"kz_89"`
	Kz93 string `json:"kz_93"`
	Von string `json:"von"`
	Zahllast string `json:"zahllast"`
	Zeitraum string `json:"zeitraum"`
	ZeitraumTyp string `json:"zeitraum_typ"`
}
