// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ContactUpdate - ContactUpdate struct
type ContactUpdate struct {
	AccountHolder string `json:"accountHolder,omitempty"`
	AcquisitionCost string `json:"acquisitionCost,omitempty"`
	AddressSupplement string `json:"addressSupplement,omitempty"`
	Attention string `json:"attention,omitempty"`
	BankName string `json:"bankName,omitempty"`
	Bic string `json:"bic,omitempty" validate:"regexp=^[A-Z]{6}[A-Z0-9]{2}([A-Z0-9]{3})?$"`
	BuyerReference string `json:"buyerReference,omitempty"`
	Category string `json:"category,omitempty"`
	CertificateAuthority string `json:"certificateAuthority,omitempty"`
	CertificateNumber string `json:"certificateNumber,omitempty"`
	CertificateParagraph string `json:"certificateParagraph,omitempty"`
	CertificateValidUntil string `json:"certificateValidUntil,omitempty"`
	City string `json:"city,omitempty"`
	CompanyName string `json:"companyName,omitempty"`
	ContactPersons interface{} `json:"contactPersons,omitempty"`
	ContactType ContactType `json:"contactType,omitempty"`
	Country CountryCode `json:"country,omitempty"`
	CreditLimit string `json:"creditLimit,omitempty"`
	CreditorAccountSkr03 string `json:"creditorAccountSkr03,omitempty"`
	CreditorAccountSkr04 string `json:"creditorAccountSkr04,omitempty"`
	Currency string `json:"currency,omitempty"`
	CustomFields interface{} `json:"customFields,omitempty"`
	CustomerNumber string `json:"customerNumber,omitempty"`
	DebitorAccountSkr03 string `json:"debitorAccountSkr03,omitempty"`
	DebitorAccountSkr04 string `json:"debitorAccountSkr04,omitempty"`
	DefaultDebitorNumber string `json:"defaultDebitorNumber,omitempty"`
	DeliveryBlock bool `json:"deliveryBlock,omitempty"`
	Department string `json:"department,omitempty"`
	DiscountDays int32 `json:"discountDays,omitempty"`
	DiscountPercentage string `json:"discountPercentage,omitempty"`
	DonationReceiptEligible bool `json:"donationReceiptEligible,omitempty"`
	Email string `json:"email,omitempty"`
	ExternalId string `json:"externalId,omitempty"`
	Fax string `json:"fax,omitempty" validate:"regexp=^\\+?[0-9\\s\\-\\(\\)]{7\\,20}$"`
	Iban string `json:"iban,omitempty" validate:"regexp=^[A-Z]{2}\\d{2}[A-Z0-9]{4\\,30}$"`
	Industry string `json:"industry,omitempty"`
	IsActive bool `json:"isActive,omitempty"`
	IsMember bool `json:"isMember,omitempty"`
	IsNonprofit bool `json:"isNonprofit,omitempty"`
	LastContactDate string `json:"lastContactDate,omitempty"`
	LastPurchaseDate string `json:"lastPurchaseDate,omitempty"`
	LeitwegId string `json:"leitwegId,omitempty"`
	LifetimeValue string `json:"lifetimeValue,omitempty"`
	MandateDate string `json:"mandateDate,omitempty"`
	MandateReference string `json:"mandateReference,omitempty"`
	MarketingConsent bool `json:"marketingConsent,omitempty"`
	MarketingConsentAt string `json:"marketingConsentAt,omitempty"`
	MarketingConsentSource string `json:"marketingConsentSource,omitempty"`
	Mobile string `json:"mobile,omitempty" validate:"regexp=^\\+?[0-9\\s\\-\\(\\)]{7\\,20}$"`
	Name string `json:"name,omitempty"`
	NextContactDate string `json:"nextContactDate,omitempty"`
	Notes string `json:"notes,omitempty"`
	OpeningBalance string `json:"openingBalance,omitempty"`
	OpeningBalanceDate string `json:"openingBalanceDate,omitempty"`
	OrderReference string `json:"orderReference,omitempty"`
	PaymentBlock bool `json:"paymentBlock,omitempty"`
	PaymentGracePeriodDays int32 `json:"paymentGracePeriodDays,omitempty"`
	PaymentMethods []string `json:"paymentMethods,omitempty"`
	PaymentTerms string `json:"paymentTerms,omitempty"`
	Phone string `json:"phone,omitempty" validate:"regexp=^\\+?[0-9\\s\\-\\(\\)]{7\\,20}$"`
	Rating int32 `json:"rating,omitempty"`
	SalesRepresentative string `json:"salesRepresentative,omitempty"`
	SepaBatchBooking bool `json:"sepaBatchBooking,omitempty"`
	SepaSequenceType SepaSequenceType `json:"sepaSequenceType,omitempty"`
	SocialMedia interface{} `json:"socialMedia,omitempty"`
	Source string `json:"source,omitempty"`
	State string `json:"state,omitempty"`
	Street string `json:"street,omitempty"`
	StreetNumber string `json:"streetNumber,omitempty"`
	SupplierNumber string `json:"supplierNumber,omitempty"`
	Tags []string `json:"tags,omitempty"`
	TaxCountry CountryCode `json:"taxCountry,omitempty"`
	TaxNumber string `json:"taxNumber,omitempty"`
	TaxOffice string `json:"taxOffice,omitempty"`
	TotalInvoices int32 `json:"totalInvoices,omitempty"`
	TotalRevenue string `json:"totalRevenue,omitempty"`
	VatId string `json:"vatId,omitempty" validate:"regexp=^[A-Z]{2}[0-9A-Z]{8\\,15}$"`
	VatIdValidated bool `json:"vatIdValidated,omitempty"`
	VatIdValidationDate string `json:"vatIdValidationDate,omitempty"`
	Website string `json:"website,omitempty"`
	Zip string `json:"zip,omitempty"`
}
