// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// BalanceSheet - BalanceSheet struct
type BalanceSheet struct {
	Assets []BalanceItem `json:"assets"`
	Balanced bool `json:"balanced"`
	EquityLiabilities []BalanceItem `json:"equity_liabilities"`
	TotalAssets string `json:"total_assets"`
	TotalEquityLiabilities string `json:"total_equity_liabilities"`
}
