// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// EmailTemplateCreate - EmailTemplateCreate struct
type EmailTemplateCreate struct {
	Body string `json:"body"`
	Name string `json:"name"`
	Status EmailTemplateStatus `json:"status"`
	Subject string `json:"subject"`
	Variables interface{} `json:"variables,omitempty"`
}
