// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ConfigFieldKindOneOf - ConfigFieldKindOneOf struct
type ConfigFieldKindOneOf struct {
	Type string `json:"type"`
}
