// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// FeatureSettings - Feature toggles for a tenant.
type FeatureSettings struct {
	Onlineshop bool `json:"onlineshop"`
	ReportBilanz bool `json:"reportBilanz"`
	ReportBwa bool `json:"reportBwa"`
	ReportEuer bool `json:"reportEuer"`
	ReportGewerbesteuer bool `json:"reportGewerbesteuer"`
	ReportGuv bool `json:"reportGuv"`
	ReportKst bool `json:"reportKst"`
	ReportUstva bool `json:"reportUstva"`
}
