// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// StillePartnerZeile - StillePartnerZeile struct
type StillePartnerZeile struct {
	Auseinandersetzungsguthaben string `json:"auseinandersetzungsguthaben"`
	Gewinnanteil string `json:"gewinnanteil"`
	Gewinnvortrag string `json:"gewinnvortrag"`
	Hinweis string `json:"hinweis,omitempty"`
	InstrumentType string `json:"instrument_type"`
	Kest string `json:"kest"`
	Name string `json:"name"`
	VerlustVerrechnungskonto string `json:"verlust_verrechnungskonto"`
	Verlustanteil string `json:"verlustanteil"`
}
