// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ShippingRule - ShippingRule struct
type ShippingRule struct {
	Carrier string `json:"carrier,omitempty"`
	Country CountryCode `json:"country,omitempty"`
	DeliveryTime string `json:"deliveryTime,omitempty"`
	IsActive bool `json:"isActive,omitempty"`
	MaxWeightKg float64 `json:"maxWeightKg,omitempty"`
	MinWeightKg float64 `json:"minWeightKg,omitempty"`
	Name string `json:"name"`
	Notes string `json:"notes,omitempty"`
	Price string `json:"price"`
	Priority int32 `json:"priority,omitempty"`
}
