// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// FristEintrag - FristEintrag struct
type FristEintrag struct {
	Bezeichnung string `json:"bezeichnung"`
	Faellig string `json:"faellig"`
	FaelligOriginal string `json:"faellig_original"`
	Hinweis string `json:"hinweis,omitempty"`
	Typ string `json:"typ"`
	Zeitraum string `json:"zeitraum"`
}
