// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CurrentInventoryValue - CurrentInventoryValue struct
type CurrentInventoryValue struct {
	History []InventoryValuePoint `json:"history"`
	ProductCount int64 `json:"product_count"`
	TotalPurchaseValue string `json:"total_purchase_value"`
	TotalSalesValue string `json:"total_sales_value"`
}
