// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Job - Job struct
type Job struct {
	Attempts int32 `json:"attempts,omitempty"`
	JobType string `json:"jobType"`
	MaxAttempts int32 `json:"maxAttempts"`
	Payload interface{} `json:"payload,omitempty"`
	RunAt string `json:"runAt,omitempty"`
	Status JobStatus `json:"status"`
}
