// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// VatSummary - VatSummary struct
type VatSummary struct {
	InputTaxItems []VatItem `json:"input_tax_items"`
	OutputTaxItems []VatItem `json:"output_tax_items"`
	TotalInputTax string `json:"total_input_tax"`
	TotalOutputTax string `json:"total_output_tax"`
	VatDue string `json:"vat_due"`
}
