// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PackingQueueItem - PackingQueueItem struct
type PackingQueueItem struct {
	CreatedAt string `json:"created_at"`
	CustomerId string `json:"customer_id"`
	DeliveryNotePrinted bool `json:"delivery_note_printed"`
	Items interface{} `json:"items"`
	ItemsCount int32 `json:"items_count"`
	LabelPrinted bool `json:"label_printed"`
	OrderNumber string `json:"order_number"`
	OrderStatus string `json:"order_status"`
	ShipmentId string `json:"shipment_id,omitempty"`
	ShippingAddress interface{} `json:"shipping_address,omitempty"`
	ShippingMethod string `json:"shipping_method"`
	TrackingNumber string `json:"tracking_number,omitempty"`
	VideoRecording string `json:"video_recording,omitempty"`
}
