// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Attachment - Attachment struct
type Attachment struct {
	ContactId string `json:"contactId,omitempty"`
	FileName string `json:"fileName"`
	FileSize int64 `json:"fileSize,omitempty"`
	MimeType string `json:"mimeType,omitempty"`
	OcrText string `json:"ocrText,omitempty"`
	OriginalName string `json:"originalName"`
	PdfaPath string `json:"pdfaPath,omitempty"`
	Sha256Hash string `json:"sha256Hash,omitempty"`
	UploadedBy string `json:"uploadedBy,omitempty"`
}
