// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// KonzernExportResponse - KonzernExportResponse struct
type KonzernExportResponse struct {
	CsvContent string `json:"csv_content"`
	Filename string `json:"filename"`
}
