// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// EmissionsExportResponse - EmissionsExportResponse struct
type EmissionsExportResponse struct {
	CsvContent string `json:"csv_content"`
	Filename string `json:"filename"`
}
