// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Absence - Absence struct
type Absence struct {
	AbsenceType AbsenceType `json:"absenceType,omitempty"`
	ApprovedAt string `json:"approvedAt,omitempty"`
	ApprovedBy string `json:"approvedBy,omitempty"`
	CreatedAt string `json:"createdAt,omitempty"`
	DeletedAt string `json:"deletedAt,omitempty"`
	EmployeeId string `json:"employeeId,omitempty"`
	EndDate string `json:"endDate,omitempty"`
	Id string `json:"id,omitempty"`
	Notes string `json:"notes,omitempty"`
	StartDate string `json:"startDate,omitempty"`
	Status AbsenceStatus `json:"status,omitempty"`
	TenantId string `json:"tenantId,omitempty"`
	UpdatedAt string `json:"updatedAt,omitempty"`
}
