// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ProductVariantUpdate - ProductVariantUpdate struct
type ProductVariantUpdate struct {
	Barcode string `json:"barcode,omitempty"`
	ImageLink string `json:"imageLink,omitempty"`
	IsActive bool `json:"isActive,omitempty"`
	Name string `json:"name,omitempty"`
	OptionValues interface{} `json:"optionValues,omitempty"`
	Price string `json:"price,omitempty"`
	PriceDelta string `json:"priceDelta,omitempty"`
	ProductId string `json:"productId,omitempty"`
	Sku string `json:"sku,omitempty"`
	StockQuantity int64 `json:"stockQuantity,omitempty"`
}
