// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Bom - Bom struct
type Bom struct {
	Components interface{} `json:"components,omitempty"`
	Description string `json:"description,omitempty"`
	Name string `json:"name"`
	OutputQuantity int64 `json:"outputQuantity,omitempty"`
	ProductId string `json:"productId"`
	Status BomStatus `json:"status,omitempty"`
}
