// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CartItemInput - CartItemInput struct
type CartItemInput struct {
	ProductId string `json:"product_id"`
	Quantity int32 `json:"quantity"`
}
