// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// WebhookEvent - WebhookEvent struct
type WebhookEvent struct {
	Attempts int32 `json:"attempts,omitempty"`
	Channel string `json:"channel,omitempty"`
	Direction WebhookDirection `json:"direction"`
	EventType string `json:"eventType"`
	LastError string `json:"lastError,omitempty"`
	Payload interface{} `json:"payload,omitempty"`
	Status WebhookEventStatus `json:"status,omitempty"`
}
