// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Quotation - Quotation struct
type Quotation struct {
	Address interface{} `json:"address,omitempty"`
	ContactId string `json:"contactId,omitempty"`
	ContactName string `json:"contactName,omitempty"`
	Currency string `json:"currency"`
	ExpirationDate string `json:"expirationDate,omitempty"`
	Files interface{} `json:"files,omitempty"`
	Introduction string `json:"introduction,omitempty"`
	LineItems interface{} `json:"lineItems,omitempty"`
	PrecedingSalesVoucherId string `json:"precedingSalesVoucherId,omitempty"`
	PrecedingSalesVoucherType PrecedingSalesVoucherType `json:"precedingSalesVoucherType,omitempty"`
	QuotationNumber string `json:"quotationNumber,omitempty"`
	Remark string `json:"remark,omitempty"`
	Subtotal string `json:"subtotal,omitempty"`
	TaxCondition string `json:"taxCondition,omitempty"`
	Title string `json:"title,omitempty"`
	TotalAmount string `json:"totalAmount,omitempty"`
	TotalTax string `json:"totalTax,omitempty"`
	VoucherDate string `json:"voucherDate"`
	VoucherStatus VoucherStatus `json:"voucherStatus"`
}
