// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// AiSuggestion - AiSuggestion struct
type AiSuggestion struct {
	Confidence float64 `json:"confidence"`
	Reasoning string `json:"reasoning"`
	SuggestedPriority string `json:"suggested_priority,omitempty"`
	SuggestedReply string `json:"suggested_reply"`
	SuggestedStatus string `json:"suggested_status,omitempty"`
	ToolCalls []string `json:"tool_calls"`
}
