// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// HebesatzLookup - HebesatzLookup struct
type HebesatzLookup struct {
	Bundesland string `json:"bundesland"`
	CountryCode string `json:"country_code"`
	GemeindeName string `json:"gemeinde_name"`
	Gemeindeschluessel string `json:"gemeindeschluessel"`
	HebesatzGewerbesteuer float64 `json:"hebesatz_gewerbesteuer"`
	HebesatzGrundsteuerB float64 `json:"hebesatz_grundsteuer_b,omitempty"`
	Jahr int32 `json:"jahr"`
	Landkreis string `json:"landkreis,omitempty"`
	ValidFrom string `json:"valid_from"`
	ValidTo string `json:"valid_to,omitempty"`
}
