// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// AnlageGErgebnis - AnlageGErgebnis struct
type AnlageGErgebnis struct {
	GewinnVerlust string `json:"gewinn_verlust"`
	GewstGezahlt string `json:"gewst_gezahlt"`
	GewstMessbetragApprox string `json:"gewst_messbetrag_approx"`
	GewstPflichtig bool `json:"gewst_pflichtig"`
	Jahr int32 `json:"jahr"`
	KfzHinweise []AnlageGKfzHinweis `json:"kfz_hinweise"`
}
