// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// UserTenantInfo - UserTenantInfo struct
type UserTenantInfo struct {
	CustomDomain string `json:"custom_domain,omitempty"`
	Role string `json:"role"`
	Subdomain string `json:"subdomain,omitempty"`
	TenantId string `json:"tenant_id"`
	TenantName string `json:"tenant_name"`
}
