// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PriceTier - PriceTier struct
type PriceTier struct {
	CustomerGroupId string `json:"customerGroupId,omitempty"`
	MinQuantity int64 `json:"minQuantity,omitempty"`
	ProductId string `json:"productId"`
	UnitPrice string `json:"unitPrice"`
}
