// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// BomUpdate - BomUpdate struct
type BomUpdate struct {
	Components interface{} `json:"components,omitempty"`
	Description string `json:"description,omitempty"`
	Name string `json:"name,omitempty"`
	OutputQuantity int64 `json:"outputQuantity,omitempty"`
	ProductId string `json:"productId,omitempty"`
	Status BomStatus `json:"status,omitempty"`
}
