// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OrderCreate - OrderCreate struct
type OrderCreate struct {
	AuditLog interface{} `json:"auditLog,omitempty"`
	Currency string `json:"currency"`
	CustomerId string `json:"customerId"`
	ExternalReference string `json:"externalReference,omitempty"`
	InvoiceAddress interface{} `json:"invoiceAddress,omitempty"`
	Items interface{} `json:"items,omitempty"`
	Language LanguageCode `json:"language,omitempty"`
	OrderStatus OrderStatus `json:"orderStatus"`
	PaymentMethod PaymentMethod `json:"paymentMethod"`
	ShippingAddress interface{} `json:"shippingAddress,omitempty"`
	ShippingCost string `json:"shippingCost"`
	ShippingMethod string `json:"shippingMethod"`
	ShippingWeight string `json:"shippingWeight"`
	Tags []string `json:"tags"`
	TotalCost string `json:"totalCost"`
}
