// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// BwaReport - BwaReport struct
type BwaReport struct {
	Expenses BwaExpenses `json:"expenses"`
	GeneratedAt string `json:"generated_at"`
	Period string `json:"period"`
	Revenue BwaRevenue `json:"revenue"`
	Summary BwaSummary `json:"summary"`
}
