// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// EksErgebnis - EksErgebnis struct
type EksErgebnis struct {
	Gesamtergebnis string `json:"gesamtergebnis"`
	Monate []EksMonatsWert `json:"monate"`
	PrognoseNaechste6Monate string `json:"prognose_naechste_6_monate"`
	SummeAusgaben string `json:"summe_ausgaben"`
	SummeEinnahmen string `json:"summe_einnahmen"`
	ZeitraumBis string `json:"zeitraum_bis"`
	ZeitraumVon string `json:"zeitraum_von"`
}
