// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ActivityCreate - ActivityCreate struct
type ActivityCreate struct {
	ActivityType ActivityType `json:"activityType"`
	AssignedTo string `json:"assignedTo,omitempty"`
	ContactId string `json:"contactId,omitempty"`
	Description string `json:"description,omitempty"`
	DueDate string `json:"dueDate,omitempty"`
	ReminderDate string `json:"reminderDate,omitempty"`
	Status ActivityStatus `json:"status"`
	Subject string `json:"subject"`
}
