// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// VoucherCreate - VoucherCreate struct
type VoucherCreate struct {
	CategoryId string `json:"categoryId,omitempty"`
	ContactId string `json:"contactId,omitempty"`
	ContactName string `json:"contactName,omitempty"`
	Currency string `json:"currency"`
	Description string `json:"description,omitempty"`
	FileAttachments interface{} `json:"fileAttachments,omitempty"`
	LineItems interface{} `json:"lineItems,omitempty"`
	Metadata interface{} `json:"metadata,omitempty"`
	Notes string `json:"notes,omitempty"`
	OpenAmount string `json:"openAmount,omitempty"`
	PaidDate string `json:"paidDate,omitempty"`
	PaymentStatus PaymentStatus `json:"paymentStatus,omitempty"`
	TaxAmounts interface{} `json:"taxAmounts,omitempty"`
	TaxCondition string `json:"taxCondition,omitempty"`
	TotalGrossAmount string `json:"totalGrossAmount,omitempty"`
	TotalNetAmount string `json:"totalNetAmount,omitempty"`
	VoucherDate string `json:"voucherDate"`
	VoucherNumber string `json:"voucherNumber,omitempty"`
	VoucherStatus VoucherStatus `json:"voucherStatus"`
	VoucherType VoucherType `json:"voucherType"`
}
