// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// DatevBookingPreview - DatevBookingPreview struct
type DatevBookingPreview struct {
	AccountNumber string `json:"account_number"`
	DebitCredit string `json:"debit_credit"`
	DocumentDate string `json:"document_date"`
	DocumentText string `json:"document_text"`
	NetAmount string `json:"net_amount"`
	OppositeAccount string `json:"opposite_account"`
	TaxAmount string `json:"tax_amount,omitempty"`
	TaxRate string `json:"tax_rate,omitempty"`
}
