// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ReturnOrder - ReturnOrder struct
type ReturnOrder struct {
	CustomerContactId string `json:"customerContactId,omitempty"`
	CustomerName string `json:"customerName,omitempty"`
	LineItems interface{} `json:"lineItems,omitempty"`
	Notes string `json:"notes,omitempty"`
	OrderId string `json:"orderId,omitempty"`
	OrderNumber string `json:"orderNumber,omitempty"`
	ReturnNumber string `json:"returnNumber"`
	ReturnReason string `json:"returnReason,omitempty"`
	Status ReturnOrderStatus `json:"status"`
	WarehouseId string `json:"warehouseId,omitempty"`
}
