// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Shareholder - Shareholder struct
type Shareholder struct {
	Address string `json:"address,omitempty"`
	BirthDate string `json:"birthDate,omitempty"`
	Email string `json:"email,omitempty"`
	FirstName string `json:"firstName,omitempty"`
	LastName string `json:"lastName,omitempty"`
	ShareNumber string `json:"shareNumber,omitempty"`
	Shares string `json:"shares,omitempty"`
}
