// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// LegalDocType - Legal document type (matches `DOC_TYPES` in legal_defaults.rs).
type LegalDocType struct {
}
