// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// BalanceItem - BalanceItem struct
type BalanceItem struct {
	Account string `json:"account"`
	AccountName string `json:"account_name"`
	Amount string `json:"amount"`
}
