// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// EBilanzReport - EBilanzReport struct
type EBilanzReport struct {
	AccountOverview []AccountOverview `json:"account_overview"`
	BalanceSheet BalanceSheet `json:"balance_sheet"`
	GeneratedAt string `json:"generated_at"`
	IncomeStatement IncomeStatement `json:"income_statement"`
	Period string `json:"period"`
	VatSummary VatSummary `json:"vat_summary"`
}
