// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PayrollMonth - PayrollMonth struct
type PayrollMonth struct {
	Gross string `json:"gross"`
	Month int32 `json:"month"`
	Net string `json:"net"`
}
