// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// LiquidityPosition - LiquidityPosition struct
type LiquidityPosition struct {
	AccountsPayable float64 `json:"accounts_payable"`
	AccountsReceivable float64 `json:"accounts_receivable"`
	CashAndEquivalents float64 `json:"cash_and_equivalents"`
	CurrentRatio float64 `json:"current_ratio"`
	QuickRatio float64 `json:"quick_ratio"`
	WorkingCapital float64 `json:"working_capital"`
}
