// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OrderConfirmationCreate - OrderConfirmationCreate struct
type OrderConfirmationCreate struct {
	Address interface{} `json:"address,omitempty"`
	ConfirmationNumber string `json:"confirmationNumber,omitempty"`
	ContactId string `json:"contactId,omitempty"`
	ContactName string `json:"contactName,omitempty"`
	Currency string `json:"currency"`
	Files interface{} `json:"files,omitempty"`
	Introduction string `json:"introduction,omitempty"`
	LineItems interface{} `json:"lineItems,omitempty"`
	PrecedingSalesVoucherId string `json:"precedingSalesVoucherId,omitempty"`
	PrecedingSalesVoucherType PrecedingSalesVoucherType `json:"precedingSalesVoucherType,omitempty"`
	Remark string `json:"remark,omitempty"`
	TaxCondition string `json:"taxCondition,omitempty"`
	Title string `json:"title,omitempty"`
	VoucherDate string `json:"voucherDate"`
	VoucherStatus VoucherStatus `json:"voucherStatus"`
}
