// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GewerbesteuerErgebnis - GewerbesteuerErgebnis struct
type GewerbesteuerErgebnis struct {
	Freibetrag string `json:"freibetrag"`
	Gesamtbelastung string `json:"gesamtbelastung"`
	Gewerbeertrag string `json:"gewerbeertrag"`
	Hebesatz string `json:"hebesatz"`
	Jahr int32 `json:"jahr"`
	Koerperschaftsteuer string `json:"koerperschaftsteuer"`
	Land string `json:"land"`
	Messbetrag string `json:"messbetrag"`
	Steuer string `json:"steuer"`
	SteuerArt string `json:"steuer_art"`
}
