// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PayrollSummaryItem - PayrollSummaryItem struct
type PayrollSummaryItem struct {
	EmployeeCount int32 `json:"employee_count"`
	Month string `json:"month"`
	Status PayrollRunStatus `json:"status"`
	TotalEmployerCost string `json:"total_employer_cost"`
	TotalGross string `json:"total_gross"`
	TotalNet string `json:"total_net"`
	Year int32 `json:"year"`
}
