// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PaymentCondition - PaymentCondition struct
type PaymentCondition struct {
	DiscountDays int32 `json:"discount_days"`
	DiscountPercentage float64 `json:"discount_percentage"`
	Id string `json:"id"`
	Name string `json:"name"`
	PaymentTermDays int32 `json:"payment_term_days"`
}
