// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// InstituteCheckItem - InstituteCheckItem struct
type InstituteCheckItem struct {
	Exists bool `json:"exists"`
	Name string `json:"name"`
	Source string `json:"source"`
}
