// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// InventoryValuePoint - InventoryValuePoint struct
type InventoryValuePoint struct {
	ProductCount int64 `json:"product_count"`
	RecordedAt string `json:"recorded_at"`
	TotalPurchaseValue string `json:"total_purchase_value"`
	TotalSalesValue string `json:"total_sales_value"`
}
