// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// YearlyPayrollSummary - YearlyPayrollSummary struct
type YearlyPayrollSummary struct {
	AvgEmployeeCount int32 `json:"avg_employee_count"`
	Months []PayrollSummaryItem `json:"months"`
	Year int32 `json:"year"`
	YearlyEmployerCost string `json:"yearly_employer_cost"`
	YearlyGross string `json:"yearly_gross"`
	YearlyNet string `json:"yearly_net"`
}
