// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GroupFigureCreate - GroupFigureCreate struct
type GroupFigureCreate struct {
	Bilanzsumme string `json:"bilanzsumme,omitempty"`
	ExemptionClaimed bool `json:"exemptionClaimed,omitempty"`
	Mitarbeiter int64 `json:"mitarbeiter,omitempty"`
	NettoUmsatz string `json:"nettoUmsatz,omitempty"`
	ParentName string `json:"parentName,omitempty"`
	ParentSitus string `json:"parentSitus,omitempty"`
}
