// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CouponValidation - CouponValidation struct
type CouponValidation struct {
	Code string `json:"code"`
	DiscountType string `json:"discount_type"`
	DiscountValue string `json:"discount_value"`
	DiscountedAmount string `json:"discounted_amount"`
	MaxDiscountAmount string `json:"max_discount_amount,omitempty"`
	Reason string `json:"reason,omitempty"`
	Valid bool `json:"valid"`
}
