// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ProductUpdate - ProductUpdate struct
type ProductUpdate struct {
	Availability string `json:"availability,omitempty"`
	Barcode string `json:"barcode,omitempty"`
	Brand string `json:"brand,omitempty"`
	CategoryId string `json:"categoryId,omitempty"`
	Condition string `json:"condition,omitempty"`
	DefaultLedgerAccount string `json:"defaultLedgerAccount,omitempty"`
	DefaultPrice string `json:"defaultPrice,omitempty"`
	DefaultPriceFormulaId string `json:"defaultPriceFormulaId,omitempty"`
	DefaultTaxRate string `json:"defaultTaxRate,omitempty"`
	Description string `json:"description,omitempty"`
	Gtin string `json:"gtin,omitempty"`
	Height string `json:"height,omitempty"`
	ImageLink string `json:"imageLink,omitempty"`
	Images interface{} `json:"images,omitempty"`
	IsTaxable bool `json:"isTaxable,omitempty"`
	Length string `json:"length,omitempty"`
	Link string `json:"link,omitempty"`
	MaxStock int64 `json:"maxStock,omitempty"`
	MinStock int64 `json:"minStock,omitempty"`
	Mpn string `json:"mpn,omitempty"`
	Name string `json:"name,omitempty"`
	PackageHeight string `json:"packageHeight,omitempty"`
	PackageLength string `json:"packageLength,omitempty"`
	PackageWeightUnit string `json:"packageWeightUnit,omitempty"`
	PackageWeightValue string `json:"packageWeightValue,omitempty"`
	PackageWidth string `json:"packageWidth,omitempty"`
	ProductCode string `json:"productCode,omitempty"`
	ProductType string `json:"productType,omitempty"`
	PurchasePrice string `json:"purchasePrice,omitempty"`
	ReorderQuantity int64 `json:"reorderQuantity,omitempty"`
	SalePrice string `json:"salePrice,omitempty"`
	ShippingPrice string `json:"shippingPrice,omitempty"`
	ShippingRequiresInsurance bool `json:"shippingRequiresInsurance,omitempty"`
	Sku string `json:"sku,omitempty"`
	StockQuantity int64 `json:"stockQuantity,omitempty"`
	Tags interface{} `json:"tags,omitempty"`
	TaxPrice string `json:"taxPrice,omitempty"`
	TrackBatch bool `json:"trackBatch,omitempty"`
	TrackSerial bool `json:"trackSerial,omitempty"`
	Unit interface{} `json:"unit,omitempty"`
	WeightUnit string `json:"weightUnit,omitempty"`
	WeightValue string `json:"weightValue,omitempty"`
	Width string `json:"width,omitempty"`
}
