// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// WebhookEventStatus - Webhook event delivery status: accepted | delivered | failed.
type WebhookEventStatus struct {
}
