// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// DeliveryAppointment - DeliveryAppointment struct
type DeliveryAppointment struct {
	Email string `json:"email"`
	Notes string `json:"notes,omitempty"`
	Phone string `json:"phone,omitempty"`
	RequestedDate string `json:"requestedDate"`
	Status DeliveryAppointmentStatus `json:"status"`
	SupplierName string `json:"supplierName"`
	TimeSlot string `json:"timeSlot,omitempty"`
	WarehouseId string `json:"warehouseId"`
}
