// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ProductVariantCreate - ProductVariantCreate struct
type ProductVariantCreate struct {
	Barcode string `json:"barcode,omitempty"`
	ImageLink string `json:"imageLink,omitempty"`
	IsActive bool `json:"isActive,omitempty"`
	Name string `json:"name,omitempty"`
	OptionValues interface{} `json:"optionValues,omitempty"`
	Price string `json:"price,omitempty"`
	PriceDelta string `json:"priceDelta,omitempty"`
	ProductId string `json:"productId"`
	Sku string `json:"sku"`
	StockQuantity int64 `json:"stockQuantity,omitempty"`
}
