// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// DhlCredentials - DhlCredentials struct
type DhlCredentials struct {
	ApiKey string `json:"api_key"`
	ClientId string `json:"client_id,omitempty"`
	ClientSecret string `json:"client_secret,omitempty"`
}
