// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// UmsatzsteuerReport - UmsatzsteuerReport struct
type UmsatzsteuerReport struct {
	GeneratedAt string `json:"generated_at"`
	InputTax []VatDetail `json:"input_tax"`
	OutputTax []VatDetail `json:"output_tax"`
	Period string `json:"period"`
	TotalInputTax string `json:"total_input_tax"`
	TotalOutputTax string `json:"total_output_tax"`
	VatPayable string `json:"vat_payable"`
	VatRefund string `json:"vat_refund"`
}
