// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ImportTestRequest - ImportTestRequest struct
type ImportTestRequest struct {
	ApiKey string `json:"apiKey"`
	Provider string `json:"provider"`
}
