// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// DeliveryDateUpdate - DeliveryDateUpdate struct
type DeliveryDateUpdate struct {
	CustomerId string `json:"customerId,omitempty"`
	FulfilledDate string `json:"fulfilledDate,omitempty"`
	Note string `json:"note,omitempty"`
	OrderNumber string `json:"orderNumber,omitempty"`
	OriginalDate string `json:"originalDate,omitempty"`
	ProductId string `json:"productId,omitempty"`
	PromisedDate string `json:"promisedDate,omitempty"`
	Status DeliveryDateStatus `json:"status,omitempty"`
}
