// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ActivityUpdate - ActivityUpdate struct
type ActivityUpdate struct {
	ActivityType ActivityType `json:"activityType,omitempty"`
	AssignedTo string `json:"assignedTo,omitempty"`
	ContactId string `json:"contactId,omitempty"`
	Description string `json:"description,omitempty"`
	DueDate string `json:"dueDate,omitempty"`
	ReminderDate string `json:"reminderDate,omitempty"`
	Status ActivityStatus `json:"status,omitempty"`
	Subject string `json:"subject,omitempty"`
}
