// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// EmissionFactorResponse - EmissionFactorResponse struct
type EmissionFactorResponse struct {
	CategoryId string `json:"category_id"`
	KgCo2ePerUnit float64 `json:"kg_co2e_per_unit"`
	NameDe string `json:"name_de"`
	Source string `json:"source"`
	Unit string `json:"unit"`
	Version string `json:"version"`
}
