// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ApiResponseUserProfile - ApiResponseUserProfile struct
type ApiResponseUserProfile struct {
	Data ApiResponseUserProfileData `json:"data,omitempty"`
	Error string `json:"error,omitempty"`
	Message string `json:"message,omitempty"`
	Success bool `json:"success"`
}
