// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Verfahrensdokumentation - Verfahrensdokumentation struct
type Verfahrensdokumentation struct {
	Entries []ComplianceEntry `json:"entries"`
	GeneratedAt string `json:"generated_at"`
	Title string `json:"title"`
	Version string `json:"version"`
}
