// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OffenlegungReport - OffenlegungReport struct
type OffenlegungReport struct {
	Deadline string `json:"deadline"`
	DeadlineMonths int32 `json:"deadline_months"`
	Items []OffenlegungItem `json:"items"`
	Kapitalmarktorientiert bool `json:"kapitalmarktorientiert"`
	Note string `json:"note"`
	Year int32 `json:"year"`
}
