// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ApplicationStatusDto - ApplicationStatusDto struct
type ApplicationStatusDto struct {
	PostingId string `json:"postingId,omitempty"`
	Status string `json:"status"`
}
