// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PluginErrorOneOf4 - PluginErrorOneOf4 struct
type PluginErrorOneOf4 struct {
	DatabaseError []map[string]interface{} `json:"DatabaseError"`
}
