// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ApiResponseVecUserTenantInfo - ApiResponseVecUserTenantInfo struct
type ApiResponseVecUserTenantInfo struct {
	Data []ApiResponseVecUserTenantInfoDataInner `json:"data,omitempty"`
	Error string `json:"error,omitempty"`
	Message string `json:"message,omitempty"`
	Success bool `json:"success"`
}
