// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ProviderInfo - ProviderInfo struct
type ProviderInfo struct {
	DisplayName string `json:"display_name"`
	Name string `json:"name"`
	RequiresApiKey bool `json:"requires_api_key"`
	Services []string `json:"services"`
	SupportsLabelCreation bool `json:"supports_label_creation"`
	SupportsRateEstimation bool `json:"supports_rate_estimation"`
	SupportsTracking bool `json:"supports_tracking"`
}
