// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ImportStartRequest - ImportStartRequest struct
type ImportStartRequest struct {
	ApiKey string `json:"apiKey"`
	Provider string `json:"provider"`
	Years []int32 `json:"years"`
}
