// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// KostenVorschau - KostenVorschau struct
type KostenVorschau struct {
	Eintraege []KostenEintrag `json:"eintraege"`
	Gesamt string `json:"gesamt"`
}
