// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Declaration - Declaration struct
type Declaration struct {
	DeclarationType DeclarationType `json:"declarationType,omitempty"`
	IsCurrent bool `json:"isCurrent,omitempty"`
	Text string `json:"text,omitempty"`
	ValidFrom string `json:"validFrom,omitempty"`
	Version string `json:"version,omitempty"`
}
