// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PosRegister - A point-of-sale register (Kasse). Registers are the billable unit of the POS feature: each active register costs a monthly fee per tenant, billed through Paddle. `status`: `active` | `disabled`.
type PosRegister struct {
	Name string `json:"name"`
	Status PosRegisterStatus `json:"status,omitempty"`
}
