// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// NewVersionRequest - Body for uploading a new version. Bytes must already be stored under `file_name` via the object storage API.
type NewVersionRequest struct {
	FileName string `json:"fileName"`
	FileSize int64 `json:"fileSize,omitempty"`
	MimeType string `json:"mimeType,omitempty"`
	OriginalName string `json:"originalName,omitempty"`
	Sha256Hash string `json:"sha256Hash,omitempty"`
}
