// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GuVReport - GuVReport struct
type GuVReport struct {
	Expenses []GuVItem `json:"expenses"`
	GeneratedAt string `json:"generated_at"`
	NetIncome string `json:"net_income"`
	Period string `json:"period"`
	Revenue []GuVItem `json:"revenue"`
	TotalExpenses string `json:"total_expenses"`
	TotalRevenue string `json:"total_revenue"`
}
