// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ResolvedPriceResponse - ResolvedPriceResponse struct
type ResolvedPriceResponse struct {
	IsListPrice bool `json:"isListPrice"`
	PriceTierId string `json:"priceTierId,omitempty"`
	ProductId string `json:"productId"`
	Quantity int64 `json:"quantity"`
	UnitPrice string `json:"unitPrice"`
}
