// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TotpEnableRequest - TotpEnableRequest struct
type TotpEnableRequest struct {
	Code string `json:"code"`
}
