// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// KontoReport - KontoReport struct
type KontoReport struct {
	GeneratedAt string `json:"generated_at"`
	Konten []KontoItem `json:"konten"`
	Period string `json:"period"`
}
