// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TimelineEvent - Single timeline entry aggregated from the contact's activity across all related modules (communications, quotations, orders, invoices, documents).
type TimelineEvent struct {
	Date string `json:"date"`
	Detail string `json:"detail,omitempty"`
	Id string `json:"id"`
	Status string `json:"status,omitempty"`
	Title string `json:"title"`
	Type string `json:"type"`
}
