// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PublicDeliveryAppointmentResponse - PublicDeliveryAppointmentResponse struct
type PublicDeliveryAppointmentResponse struct {
	AppointmentId string `json:"appointmentId"`
	ConfirmationHint string `json:"confirmationHint"`
	Message string `json:"message"`
	Status string `json:"status"`
}
