// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CreateConnectionRequest - CreateConnectionRequest struct
type CreateConnectionRequest struct {
	ApiKey string `json:"api_key,omitempty"`
	ApiSecret string `json:"api_secret,omitempty"`
	Config interface{} `json:"config,omitempty"`
	Label string `json:"label"`
	Platform string `json:"platform"`
	ShopDomain string `json:"shop_domain,omitempty"`
}
