// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PayrollSummary - PayrollSummary struct
type PayrollSummary struct {
	FirstName string `json:"firstName"`
	HourlyGross string `json:"hourlyGross,omitempty"`
	Id string `json:"id"`
	JobTitle string `json:"jobTitle"`
	LastName string `json:"lastName"`
	MonthlySalary string `json:"monthlySalary,omitempty"`
	Months []PayrollMonth `json:"months"`
	WeeklyHours string `json:"weeklyHours,omitempty"`
	Year int32 `json:"year"`
}
