// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TrackOrderRequest - Refresh tracking for a shipment from the live carrier API and store the latest status + events on the shipment row.
type TrackOrderRequest struct {
	Email string `json:"email"`
	OrderNumber string `json:"order_number"`
}
