// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// RecurringTemplateCreate - RecurringTemplateCreate struct
type RecurringTemplateCreate struct {
	EndDate string `json:"endDate,omitempty"`
	ExecutionInterval string `json:"executionInterval"`
	ExecutionStatus ExecutionStatus `json:"executionStatus"`
	Finalize bool `json:"finalize,omitempty"`
	LastExecutedAt string `json:"lastExecutedAt,omitempty"`
	Name string `json:"name"`
	NextExecutionAt string `json:"nextExecutionAt,omitempty"`
	StartDate string `json:"startDate"`
	TemplateType RecurringTemplateType `json:"templateType"`
	VoucherData interface{} `json:"voucherData,omitempty"`
}
