// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// SuitabilityRequest - SuitabilityRequest struct
type SuitabilityRequest struct {
	CustomerAnnualVolume int32 `json:"customer_annual_volume,omitempty"`
	Items []CartItemInput `json:"items"`
	Recipient Address `json:"recipient"`
	Sender Address `json:"sender"`
}
