// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PlausibilityReport - PlausibilityReport struct
type PlausibilityReport struct {
	Checks []PlausibilityCheck `json:"checks"`
	GeneratedAt string `json:"generated_at"`
	Summary PlausibilitySummary `json:"summary"`
}
