// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ApiResponseVecTeam - ApiResponseVecTeam struct
type ApiResponseVecTeam struct {
	Data []ApiResponseTeamData `json:"data,omitempty"`
	Error string `json:"error,omitempty"`
	Message string `json:"message,omitempty"`
	Success bool `json:"success"`
}
