// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ForgotPasswordRequest - ForgotPasswordRequest struct
type ForgotPasswordRequest struct {
	Email string `json:"email"`
}
