// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Model - Model struct
type Model struct {
	BackupCodes []string `json:"backup_codes"`
	CreatedAt string `json:"created_at"`
	DeletedAt string `json:"deleted_at,omitempty"`
	Email string `json:"email"`
	EmailVerified bool `json:"email_verified"`
	Id string `json:"id"`
	IsActive bool `json:"is_active"`
	IsTotpEnabled bool `json:"is_totp_enabled"`
	LastLogin string `json:"last_login,omitempty"`
	Name string `json:"name"`
	OauthId string `json:"oauth_id,omitempty"`
	OauthProvider string `json:"oauth_provider,omitempty"`
	PasswordChangedAt string `json:"password_changed_at,omitempty"`
	PasswordHash string `json:"password_hash"`
	Picture string `json:"picture,omitempty"`
	PrivacyAcceptedAt string `json:"privacy_accepted_at,omitempty"`
	TotpSecret string `json:"totp_secret,omitempty"`
	UpdatedAt string `json:"updated_at"`
}
