// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// InstituteStatus - InstituteStatus struct
type InstituteStatus struct {
	Checklist []InstituteCheckItem `json:"checklist"`
	Deadlines InstituteDeadlines `json:"deadlines"`
	InstituteType string `json:"instituteType"`
	Kapitalmarktorientiert bool `json:"kapitalmarktorientiert"`
}
