// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// WarehouseCreate - WarehouseCreate struct
type WarehouseCreate struct {
	AddressCity string `json:"addressCity,omitempty"`
	AddressCountry CountryCode `json:"addressCountry,omitempty"`
	AddressStreet string `json:"addressStreet,omitempty"`
	AddressZip string `json:"addressZip,omitempty"`
	BinLocations interface{} `json:"binLocations,omitempty"`
	Code string `json:"code"`
	IsActive bool `json:"isActive,omitempty"`
	IsDefault bool `json:"isDefault,omitempty"`
	Name string `json:"name"`
	Notes string `json:"notes,omitempty"`
}
