// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GdprTenant - GdprTenant struct
type GdprTenant struct {
	Name string `json:"name"`
	Role string `json:"role"`
	TenantId string `json:"tenantId"`
}
