// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ElsterStatus - ElsterStatus struct
type ElsterStatus struct {
	CertConfigured bool `json:"cert_configured"`
	EricAvailable bool `json:"eric_available"`
	EricVersion string `json:"eric_version,omitempty"`
	FeatureEnabled bool `json:"feature_enabled"`
	Hint string `json:"hint"`
	Mode string `json:"mode"`
	VendorIdConfigured bool `json:"vendor_id_configured"`
}
