// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CashflowReport - CashflowReport struct
type CashflowReport struct {
	ClosingBalance float64 `json:"closing_balance"`
	FinancingCashflow float64 `json:"financing_cashflow"`
	InvestingCashflow float64 `json:"investing_cashflow"`
	NetCashflow float64 `json:"net_cashflow"`
	OpeningBalance float64 `json:"opening_balance"`
	OperatingCashflow float64 `json:"operating_cashflow"`
	Period string `json:"period"`
}
