// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// KstErgebnis - KstErgebnis struct
type KstErgebnis struct {
	Gesamt string `json:"gesamt"`
	Gesamtbelastung string `json:"gesamtbelastung"`
	Gewerbesteuer string `json:"gewerbesteuer"`
	Gewinn string `json:"gewinn"`
	IstKapitalgesellschaft bool `json:"ist_kapitalgesellschaft"`
	Jahr int32 `json:"jahr"`
	Koerperschaftsteuer string `json:"koerperschaftsteuer"`
	Solidaritaetszuschlag string `json:"solidaritaetszuschlag"`
}
