// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Section - Section struct
type Section struct {
	BodyHtml string `json:"bodyHtml"`
	BodyHtmlEn string `json:"bodyHtmlEn"`
	Id string `json:"id"`
	Title string `json:"title"`
	TitleEn string `json:"titleEn"`
}
