// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GdprExport - GdprExport struct
type GdprExport struct {
	ActivityLog []GdprActivity `json:"activityLog"`
	ApiKeys []GdprApiKey `json:"apiKeys"`
	Billing []GdprBillingInfo `json:"billing"`
	ExportedAt string `json:"exportedAt"`
	GeneratedByAi bool `json:"generatedByAi"`
	Notifications []GdprNotification `json:"notifications"`
	RefreshTokens []GdprRefreshToken `json:"refreshTokens"`
	Tenants []GdprTenant `json:"tenants"`
	UsageEvents []GdprUsageEvent `json:"usageEvents"`
	User GdprUser `json:"user"`
}
