// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ProductionOrderStatusUpdate - Status update request.
type ProductionOrderStatusUpdate struct {
	Status string `json:"status"`
}
