// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TrackOrderResponse - TrackOrderResponse struct
type TrackOrderResponse struct {
	OrderNumber string `json:"order_number"`
	OrderStatus string `json:"order_status"`
	Shipments []TrackedShipment `json:"shipments"`
}
