// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// SupplierInvoice - SupplierInvoice struct
type SupplierInvoice struct {
	Currency string `json:"currency,omitempty"`
	GoodsReceiptId string `json:"goodsReceiptId,omitempty"`
	InvoiceDate string `json:"invoiceDate"`
	InvoiceNumber string `json:"invoiceNumber"`
	LineItems interface{} `json:"lineItems"`
	Notes string `json:"notes,omitempty"`
	PurchaseOrderId string `json:"purchaseOrderId,omitempty"`
	Status SupplierInvoiceStatus `json:"status"`
	SupplierContactId string `json:"supplierContactId,omitempty"`
	SupplierName string `json:"supplierName,omitempty"`
	TotalGrossAmount string `json:"totalGrossAmount,omitempty"`
	TotalNetAmount string `json:"totalNetAmount,omitempty"`
}
