// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// BudgetKategorie - BudgetKategorie struct
type BudgetKategorie struct {
	Budget string `json:"budget"`
	Differenz string `json:"differenz"`
	Goal string `json:"goal,omitempty"`
	Ist string `json:"ist"`
	Kategorie string `json:"kategorie"`
}
