// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PlanFeatures - Feature flags per plan.
type PlanFeatures struct {
	Connectors bool `json:"connectors"`
	Erp bool `json:"erp"`
	FancyReports bool `json:"fancyReports"`
	TaxAutomations bool `json:"taxAutomations"`
}
