// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ChangePasswordRequest - ChangePasswordRequest struct
type ChangePasswordRequest struct {
	CurrentPassword string `json:"current_password"`
	NewPassword string `json:"new_password"`
}
