// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ApiResponseTeam - ApiResponseTeam struct
type ApiResponseTeam struct {
	Data ApiResponseTeamData `json:"data,omitempty"`
	Error string `json:"error,omitempty"`
	Message string `json:"message,omitempty"`
	Success bool `json:"success"`
}
