// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// AccountOverview - AccountOverview struct
type AccountOverview struct {
	Account string `json:"account"`
	AccountName string `json:"account_name"`
	Balance string `json:"balance"`
	CreditTotal string `json:"credit_total"`
	DebitTotal string `json:"debit_total"`
}
