// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ComplianceTrainingUpdate - ComplianceTrainingUpdate struct
type ComplianceTrainingUpdate struct {
	Assignable bool `json:"assignable,omitempty"`
	Code string `json:"code,omitempty"`
	Description string `json:"description,omitempty"`
	PassScore int32 `json:"passScore,omitempty"`
	PluginPlatform string `json:"pluginPlatform,omitempty"`
	Source TrainingSource `json:"source,omitempty"`
	Title string `json:"title,omitempty"`
	ValidityMonths int32 `json:"validityMonths,omitempty"`
}
