// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PrintLabelResponse - PrintLabelResponse struct
type PrintLabelResponse struct {
	LabelUrl string `json:"label_url,omitempty"`
	Message string `json:"message"`
	Sscc string `json:"sscc,omitempty"`
	Success bool `json:"success"`
	TrackingNumber string `json:"tracking_number,omitempty"`
}
