// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GdprRefreshToken - GdprRefreshToken struct
type GdprRefreshToken struct {
	CreatedAt string `json:"createdAt"`
	ExpiresAt string `json:"expiresAt"`
	Id string `json:"id"`
	RevokedAt string `json:"revokedAt,omitempty"`
	TenantId string `json:"tenantId"`
}
