// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ChangelogEntry - One changelog entry for a plugin release.
type ChangelogEntry struct {
	Date string `json:"date"`
	Notes string `json:"notes"`
	Version string `json:"version"`
}
