// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// SubscriptionOverview - Tenant subscription overview for the billing page: current plan, status, period end, trial state, effective limits, current usage and feature flags. Backed by Paddle Billing webhook data written into `billing_info` + `tenants.plan`, and by the canonical plans in `crate::saasy::plans`.  JSON contract (camelCase, matches the frontend): `plan`, `planName`, `priceEur`, `status`, `currentPeriodEnd`, `manageUrl`, `trialEndsAt`, `isTrialing`, `limits:{maxUsers,maxInvoicesPerMonth,maxConnectors}`, `usage:{users,invoicesThisMonth,connectors,overageSeats}`, `features:{taxAutomations,fancyReports,erp}`.
type SubscriptionOverview struct {
	CurrentPeriodEnd string `json:"currentPeriodEnd,omitempty"`
	Features PlanFeatures `json:"features"`
	IsTrialing bool `json:"isTrialing"`
	Limits PlanLimits `json:"limits"`
	ManageUrl string `json:"manageUrl,omitempty"`
	Plan string `json:"plan"`
	PlanName string `json:"planName"`
	PriceEur float64 `json:"priceEur"`
	Quantity int32 `json:"quantity,omitempty"`
	Status string `json:"status,omitempty"`
	SubscriptionId string `json:"subscriptionId,omitempty"`
	TrialEndsAt string `json:"trialEndsAt,omitempty"`
	Usage UsageSnapshot `json:"usage"`
}
