// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ProductionOrder - ProductionOrder struct
type ProductionOrder struct {
	BomId string `json:"bomId,omitempty"`
	Components interface{} `json:"components,omitempty"`
	EndDate string `json:"endDate,omitempty"`
	Notes string `json:"notes,omitempty"`
	OrderNumber string `json:"orderNumber"`
	ProductId string `json:"productId"`
	Quantity int64 `json:"quantity"`
	SourceWarehouseId string `json:"sourceWarehouseId,omitempty"`
	StartDate string `json:"startDate,omitempty"`
	Status ProductionOrderStatus `json:"status,omitempty"`
	TargetWarehouseId string `json:"targetWarehouseId,omitempty"`
}
