// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Automation - Automation struct
type Automation struct {
	AutomationKey string `json:"automationKey"`
	Config interface{} `json:"config"`
	CreatedAt string `json:"createdAt"`
	Enabled bool `json:"enabled"`
	LastRunAt string `json:"lastRunAt,omitempty"`
	NextRunAt string `json:"nextRunAt,omitempty"`
	TenantId string `json:"tenantId"`
	UpdatedAt string `json:"updatedAt"`
}
