// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// BudgetGoalRequest - BudgetGoalRequest struct
type BudgetGoalRequest struct {
	MonthlyGoal string `json:"monthly_goal"`
	Year int32 `json:"year"`
}
