// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// WebhookDirection - Webhook event direction: inbound | outbound.
type WebhookDirection struct {
}
