// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PosTableCreate - PosTableCreate struct
type PosTableCreate struct {
	CurrentOrderNumber string `json:"currentOrderNumber,omitempty"`
	Name string `json:"name"`
	Status PosTableStatus `json:"status,omitempty"`
}
