// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// EksMonatsWert - EksMonatsWert struct
type EksMonatsWert struct {
	Ausgaben string `json:"ausgaben"`
	Einnahmen string `json:"einnahmen"`
	Ergebnis string `json:"ergebnis"`
	Monat string `json:"monat"`
}
