// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PublicReturnItem - PublicReturnItem struct
type PublicReturnItem struct {
	Name string `json:"name,omitempty"`
	ProductId string `json:"productId"`
	Quantity int64 `json:"quantity"`
	Reason string `json:"reason,omitempty"`
}
