// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomerCommunicationUpdate - CustomerCommunicationUpdate struct
type CustomerCommunicationUpdate struct {
	Body string `json:"body,omitempty"`
	Channel CommunicationChannel `json:"channel,omitempty"`
	ContactId string `json:"contactId,omitempty"`
	Counterparty string `json:"counterparty,omitempty"`
	Direction CommunicationDirection `json:"direction,omitempty"`
	OccurredAt string `json:"occurredAt,omitempty"`
	Subject string `json:"subject,omitempty"`
	Tags interface{} `json:"tags,omitempty"`
}
