// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// InstituteProfileUpdate - Partial update of the institute profile.
type InstituteProfileUpdate struct {
	InstituteType string `json:"instituteType,omitempty"`
	Kapitalmarktorientiert bool `json:"kapitalmarktorientiert,omitempty"`
}
