// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ProductStock - ProductStock struct
type ProductStock struct {
	Name string `json:"name"`
	ProductId string `json:"product_id"`
	Sku string `json:"sku"`
	StockQuantity int64 `json:"stock_quantity,omitempty"`
}
