// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Shipment - Shipment struct
type Shipment struct {
	DeliveredAt string `json:"deliveredAt,omitempty"`
	LabelUrl string `json:"labelUrl,omitempty"`
	LineItemsShipment interface{} `json:"lineItemsShipment,omitempty"`
	OrderId string `json:"orderId"`
	RecipientAddress interface{} `json:"recipientAddress,omitempty"`
	ShipmentDate string `json:"shipmentDate"`
	ShippingCarrier string `json:"shippingCarrier"`
	ShippingCost string `json:"shippingCost,omitempty"`
	ShippingMethod string `json:"shippingMethod,omitempty"`
	SignedBy string `json:"signedBy,omitempty"`
	Status string `json:"status"`
	TrackingEvents interface{} `json:"trackingEvents,omitempty"`
	TrackingNumber string `json:"trackingNumber,omitempty"`
	TrackingUrl string `json:"trackingUrl,omitempty"`
	WeightKg float64 `json:"weightKg,omitempty"`
}
