// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GdprApiKey - GdprApiKey struct
type GdprApiKey struct {
	CreatedAt string `json:"createdAt"`
	ExpiresAt string `json:"expiresAt,omitempty"`
	Id string `json:"id"`
	KeyId string `json:"keyId"`
	Name string `json:"name"`
	Revoked bool `json:"revoked"`
}
