// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GenerateCountRequest - Body for the cycle-count generator: create a draft count document for a warehouse, optionally restricted to a set of product ids.
type GenerateCountRequest struct {
	Notes string `json:"notes,omitempty"`
	ProductIds []string `json:"productIds,omitempty"`
	WarehouseId string `json:"warehouseId"`
}
