// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PlausibilityCheck - PlausibilityCheck struct
type PlausibilityCheck struct {
	Detail string `json:"detail"`
	Id string `json:"id"`
	Name string `json:"name"`
	Severity Severity `json:"severity"`
	Status CheckStatus `json:"status"`
}
