// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// DatevImportRow - DatevImportRow struct
type DatevImportRow struct {
	Account string `json:"account"`
	Amount string `json:"amount"`
	BaseAmount string `json:"base_amount"`
	BaseCurrency string `json:"base_currency"`
	BookingText string `json:"booking_text"`
	BuKey string `json:"bu_key"`
	CostCenter1 string `json:"cost_center1"`
	CostCenter2 string `json:"cost_center2"`
	Currency string `json:"currency"`
	DebitCredit string `json:"debit_credit"`
	Discount string `json:"discount"`
	DocumentDate string `json:"document_date"`
	DocumentField2 string `json:"document_field2"`
	DocumentNumber string `json:"document_number"`
	EuCountryVatId string `json:"eu_country_vat_id"`
	EuTaxRate string `json:"eu_tax_rate"`
	ExchangeRate string `json:"exchange_rate"`
	OppositeAccount string `json:"opposite_account"`
}
