// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PluginPricingOneOf - PluginPricingOneOf struct
type PluginPricingOneOf struct {
	Type string `json:"type"`
}
