// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ReturnLogisticsSummary - Warehouse-level aggregation for the returns logistics dashboard.
type ReturnLogisticsSummary struct {
	ByStatus interface{} `json:"byStatus"`
	ByWarehouse []ReturnWarehouseSummary `json:"byWarehouse"`
	ItemsRestocked int64 `json:"itemsRestocked"`
	ItemsScrapped int64 `json:"itemsScrapped"`
	TotalItems int64 `json:"totalItems"`
	TotalReturns int64 `json:"totalReturns"`
}
