// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PluginPricingOneOf1 - PluginPricingOneOf1 struct
type PluginPricingOneOf1 struct {
	Price float64 `json:"price"`
	Type string `json:"type"`
}
