// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// InstrumentType - Silent-partnership instrument: \"typisch\" | \"atypisch\".
type InstrumentType struct {
}
