// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OAuthCallbackRequest - OAuthCallbackRequest struct
type OAuthCallbackRequest struct {
	Code string `json:"code"`
	Config interface{} `json:"config,omitempty"`
	ConnectionId string `json:"connection_id,omitempty"`
	Platform string `json:"platform"`
	ShopDomain string `json:"shop_domain,omitempty"`
	State string `json:"state"`
}
