// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// StilleReport - StilleReport struct
type StilleReport struct {
	Jahresueberschuss string `json:"jahresueberschuss"`
	Partners []StillePartnerZeile `json:"partners"`
	Year int32 `json:"year"`
}
