// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// KycRecord - KycRecord struct
type KycRecord struct {
	CustomerId string `json:"customerId,omitempty"`
	CustomerName string `json:"customerName,omitempty"`
	KycDate string `json:"kycDate,omitempty"`
	Notes string `json:"notes,omitempty"`
	RetentionUntil string `json:"retentionUntil,omitempty"`
	RiskAssessment string `json:"riskAssessment,omitempty"`
}
