// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PlausibilitySummary - PlausibilitySummary struct
type PlausibilitySummary struct {
	Errors int32 `json:"errors"`
	OverallStatus CheckStatus `json:"overall_status"`
	Passed int32 `json:"passed"`
	TotalChecks int32 `json:"total_checks"`
	Warnings int32 `json:"warnings"`
}
