// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// WorkflowAction - One action inside a workflow. Only `email` is supported for now.
type WorkflowAction struct {
	ActionType string `json:"action_type"`
	Body string `json:"body,omitempty"`
	Subject string `json:"subject,omitempty"`
}
