// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// UpdateSubscriptionRequest - UpdateSubscriptionRequest struct
type UpdateSubscriptionRequest struct {
	EventType string `json:"event_type,omitempty"`
	IsActive bool `json:"is_active,omitempty"`
	Name string `json:"name,omitempty"`
	Secret string `json:"secret,omitempty"`
	Url string `json:"url,omitempty"`
}
