// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// EmailTemplateUpdate - EmailTemplateUpdate struct
type EmailTemplateUpdate struct {
	Body string `json:"body,omitempty"`
	Name string `json:"name,omitempty"`
	Status EmailTemplateStatus `json:"status,omitempty"`
	Subject string `json:"subject,omitempty"`
	Variables interface{} `json:"variables,omitempty"`
}
