// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ApiResponseString - ApiResponseString struct
type ApiResponseString struct {
	Data string `json:"data,omitempty"`
	Error string `json:"error,omitempty"`
	Message string `json:"message,omitempty"`
	Success bool `json:"success"`
}
