// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// SalesVolumeItem - SalesVolumeItem struct
type SalesVolumeItem struct {
	ContactId string `json:"contact_id"`
	ContactType string `json:"contact_type"`
	LastPurchaseDate string `json:"last_purchase_date,omitempty"`
	Name string `json:"name"`
	TotalInvoices int32 `json:"total_invoices"`
	TotalRevenue string `json:"total_revenue"`
}
