// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// EuerDetailErgebnis - EuerDetailErgebnis struct
type EuerDetailErgebnis struct {
	Jahr int32 `json:"jahr"`
	Zeilen []EuerZeileDetail `json:"zeilen"`
}
