// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PluginErrorOneOf5 - PluginErrorOneOf5 struct
type PluginErrorOneOf5 struct {
	ValidationError []map[string]interface{} `json:"ValidationError"`
}
