// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// AttachmentVersion - AttachmentVersion struct
type AttachmentVersion struct {
	AttachmentId string `json:"attachmentId"`
	FileName string `json:"fileName"`
	FileSize int64 `json:"fileSize,omitempty"`
	MimeType string `json:"mimeType,omitempty"`
	OriginalName string `json:"originalName,omitempty"`
	Sha256Hash string `json:"sha256Hash,omitempty"`
	UploadedBy string `json:"uploadedBy,omitempty"`
	VersionNumber int32 `json:"versionNumber"`
}
