// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CreateTicketRequest - Request body for creating a support ticket. Wraps the generated `SupportTicketCreateDto` fields plus `message_body` which is not a Model field (used to create the initial `ticket_message`).
type CreateTicketRequest struct {
	ChannelId string `json:"channel_id,omitempty"`
	ChannelType string `json:"channel_type,omitempty"`
	CustomerEmail string `json:"customer_email,omitempty"`
	CustomerId string `json:"customer_id,omitempty"`
	CustomerName string `json:"customer_name,omitempty"`
	ExternalId string `json:"external_id,omitempty"`
	MessageBody string `json:"message_body"`
	OrderRef string `json:"order_ref,omitempty"`
	Subject string `json:"subject"`
}
