// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// UsageSnapshot - Current usage for a tenant. `overage_seats` is what billing charges 5€/seat/month on.
type UsageSnapshot struct {
	Connectors int64 `json:"connectors"`
	InvoicesThisMonth int64 `json:"invoicesThisMonth"`
	OverageSeats int64 `json:"overageSeats"`
	Users int64 `json:"users"`
}
