// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PayGapReport - PayGapReport struct
type PayGapReport struct {
	ByJobTitle []JobTitleGap `json:"by_job_title"`
	DiverseCount int32 `json:"diverse_count"`
	EmployeeCount int32 `json:"employee_count"`
	FemaleCount int32 `json:"female_count"`
	MaleCount int32 `json:"male_count"`
	MeanGapPct float64 `json:"mean_gap_pct"`
	MedianGapPct float64 `json:"median_gap_pct"`
	Quartiles []QuartileBand `json:"quartiles"`
}
