// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// StockTransfer - StockTransfer struct
type StockTransfer struct {
	LineItems interface{} `json:"lineItems"`
	Notes string `json:"notes,omitempty"`
	SourceWarehouseId string `json:"sourceWarehouseId"`
	Status StockTransferStatus `json:"status"`
	TargetWarehouseId string `json:"targetWarehouseId"`
	TransferDate string `json:"transferDate"`
	TransferNumber string `json:"transferNumber"`
}
