// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PaymentGatewayUpdate - PaymentGatewayUpdate struct
type PaymentGatewayUpdate struct {
	Config interface{} `json:"config,omitempty"`
	CreatedAt string `json:"createdAt,omitempty"`
	DeletedAt string `json:"deletedAt,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
	GatewayType GatewayType `json:"gatewayType,omitempty"`
	Label string `json:"label,omitempty"`
	UpdatedAt string `json:"updatedAt,omitempty"`
}
