// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// SupplierInvoiceStatusUpdate - SupplierInvoiceStatusUpdate struct
type SupplierInvoiceStatusUpdate struct {
	Status string `json:"status"`
}
