// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// LegalDocumentUpsert - One document to upsert (`PUT /api/v1/legal/documents` body element).
type LegalDocumentUpsert struct {
	Content string `json:"content"`
	DocType string `json:"docType"`
	Lang string `json:"lang"`
	Title string `json:"title"`
}
