// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// RecurringTemplateUpdate - RecurringTemplateUpdate struct
type RecurringTemplateUpdate struct {
	EndDate string `json:"endDate,omitempty"`
	ExecutionInterval string `json:"executionInterval,omitempty"`
	ExecutionStatus ExecutionStatus `json:"executionStatus,omitempty"`
	Finalize bool `json:"finalize,omitempty"`
	LastExecutedAt string `json:"lastExecutedAt,omitempty"`
	Name string `json:"name,omitempty"`
	NextExecutionAt string `json:"nextExecutionAt,omitempty"`
	StartDate string `json:"startDate,omitempty"`
	TemplateType RecurringTemplateType `json:"templateType,omitempty"`
	VoucherData interface{} `json:"voucherData,omitempty"`
}
