// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TaxRateCreate - TaxRateCreate struct
type TaxRateCreate struct {
	CountryCode string `json:"countryCode"`
	EffectiveFrom string `json:"effectiveFrom,omitempty"`
	IsDefault bool `json:"isDefault"`
	Name string `json:"name"`
	RatePercent int64 `json:"ratePercent"`
}
