// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ServiceAssignment - ServiceAssignment struct
type ServiceAssignment struct {
	EmployeeId string `json:"employeeId,omitempty"`
	JobId string `json:"jobId,omitempty"`
	Notes string `json:"notes,omitempty"`
	ScheduledDate string `json:"scheduledDate,omitempty"`
	ScheduledEnd string `json:"scheduledEnd,omitempty"`
	ScheduledStart string `json:"scheduledStart,omitempty"`
	Status ServiceAssignmentStatus `json:"status,omitempty"`
}
