// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PartialFeatureSettings - Partial feature toggles: `None` keeps the company-type default, `Some` overrides it.
type PartialFeatureSettings struct {
	Onlineshop bool `json:"onlineshop,omitempty"`
	ReportBilanz bool `json:"reportBilanz,omitempty"`
	ReportBwa bool `json:"reportBwa,omitempty"`
	ReportEuer bool `json:"reportEuer,omitempty"`
	ReportGewerbesteuer bool `json:"reportGewerbesteuer,omitempty"`
	ReportGuv bool `json:"reportGuv,omitempty"`
	ReportKst bool `json:"reportKst,omitempty"`
	ReportUstva bool `json:"reportUstva,omitempty"`
}
