// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PackingCompleteRequest - PackingCompleteRequest struct
type PackingCompleteRequest struct {
	Notes string `json:"notes,omitempty"`
	OrderNumber string `json:"order_number"`
	ShipmentId string `json:"shipment_id,omitempty"`
	VideoUrl string `json:"video_url,omitempty"`
}
