// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// QuizQuestion - QuizQuestion struct
type QuizQuestion struct {
	Id string `json:"id"`
	Options []string `json:"options"`
	OptionsEn []string `json:"optionsEn"`
	Question string `json:"question"`
	QuestionEn string `json:"questionEn"`
}
