// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// BilanzReport - BilanzReport struct
type BilanzReport struct {
	Aktiva []BilanzItem `json:"aktiva"`
	Balanced bool `json:"balanced"`
	GeneratedAt string `json:"generated_at"`
	Passiva []BilanzItem `json:"passiva"`
	Period string `json:"period"`
	TotalAktiva string `json:"total_aktiva"`
	TotalPassiva string `json:"total_passiva"`
}
