// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// AuthResponse - AuthResponse struct
type AuthResponse struct {
	AccessToken string `json:"access_token,omitempty"`
	Message string `json:"message,omitempty"`
	RefreshToken string `json:"refresh_token,omitempty"`
	Success bool `json:"success"`
	User Model `json:"user,omitempty"`
}
