// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Rfq - Rfq struct
type Rfq struct {
	Currency string `json:"currency,omitempty"`
	LineItems interface{} `json:"lineItems"`
	Notes string `json:"notes,omitempty"`
	RequestedDate string `json:"requestedDate"`
	ResponseDate string `json:"responseDate,omitempty"`
	RfqNumber string `json:"rfqNumber"`
	Status RfqStatus `json:"status"`
	SupplierContactId string `json:"supplierContactId,omitempty"`
	SupplierName string `json:"supplierName,omitempty"`
}
