// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// InventoryCountCreate - InventoryCountCreate struct
type InventoryCountCreate struct {
	CountDate string `json:"countDate"`
	CountNumber string `json:"countNumber"`
	LineItems interface{} `json:"lineItems"`
	Notes string `json:"notes,omitempty"`
	Status InventoryCountStatus `json:"status"`
	WarehouseId string `json:"warehouseId"`
}
