// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OrderStateUpdate - OrderStateUpdate struct
type OrderStateUpdate struct {
	SendStateToShop bool `json:"send_state_to_shop,omitempty"`
	State string `json:"state"`
}
