// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PluginError - PluginError struct
type PluginError struct {
	BadRequest []map[string]interface{} `json:"BadRequest"`
	NotFound []map[string]interface{} `json:"NotFound"`
	Unauthorized []map[string]interface{} `json:"Unauthorized"`
	InternalError []map[string]interface{} `json:"InternalError"`
	DatabaseError []map[string]interface{} `json:"DatabaseError"`
	ValidationError []map[string]interface{} `json:"ValidationError"`
	NotImplemented string `json:"NotImplemented"`
}
