// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// KonzernThresholds - KonzernThresholds struct
type KonzernThresholds struct {
	Bilanzsumme string `json:"bilanzsumme"`
	Mitarbeiter int64 `json:"mitarbeiter"`
	NettoUmsatz string `json:"netto_umsatz"`
}
