// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// SepaSequenceType - SEPA mandate sequence type (ISO 20022 mandate codes).
type SepaSequenceType struct {
}
