// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ConfigFieldKindOneOf3 - ConfigFieldKindOneOf3 struct
type ConfigFieldKindOneOf3 struct {
	Options []string `json:"options"`
	Type string `json:"type"`
}
