// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ApiResponseVecPlanDataInner - One canonical plan. `price_eur == -1.0` means custom pricing.
type ApiResponseVecPlanDataInner struct {
	Features PlanFeatures `json:"features"`
	Id string `json:"id"`
	Limits PlanLimits `json:"limits"`
	Name string `json:"name"`
	PriceEur float64 `json:"priceEur"`
}
