// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// UpdateTenantSettings - Request payload for updating tenant settings.
type UpdateTenantSettings struct {
	CompanyType CompanyType `json:"companyType"`
	Features PartialFeatureSettings `json:"features,omitempty"`
}
