// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ImportJobStatus - ImportJobStatus struct
type ImportJobStatus struct {
	Error string `json:"error,omitempty"`
	JobId string `json:"job_id"`
	Processed int64 `json:"processed"`
	Progress int32 `json:"progress"`
	Provider string `json:"provider,omitempty"`
	Stage string `json:"stage"`
	Status string `json:"status"`
	Total int64 `json:"total"`
}
