// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// InventoryCountUpdate - InventoryCountUpdate struct
type InventoryCountUpdate struct {
	CountDate string `json:"countDate,omitempty"`
	CountNumber string `json:"countNumber,omitempty"`
	LineItems interface{} `json:"lineItems,omitempty"`
	Notes string `json:"notes,omitempty"`
	Status InventoryCountStatus `json:"status,omitempty"`
	WarehouseId string `json:"warehouseId,omitempty"`
}
