// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// BilanzItem - BilanzItem struct
type BilanzItem struct {
	Amount string `json:"amount"`
	Konto string `json:"konto"`
	Name string `json:"name"`
}
