// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// BankLookup - BankLookup struct
type BankLookup struct {
	BankName string `json:"bank_name,omitempty"`
	Bic string `json:"bic,omitempty"`
	Iban string `json:"iban"`
	Nextgenpsd2Url string `json:"nextgenpsd2_url,omitempty"`
	Psd2Supported bool `json:"psd2_supported"`
}
