// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Coupon - Coupon struct
type Coupon struct {
	Code string `json:"code"`
	Description string `json:"description,omitempty"`
	DiscountType DiscountType `json:"discountType"`
	DiscountValue string `json:"discountValue"`
	ExpiresAt string `json:"expiresAt,omitempty"`
	IsActive bool `json:"isActive,omitempty"`
	IsCombineable bool `json:"isCombineable,omitempty"`
	MaxDiscountAmount string `json:"maxDiscountAmount,omitempty"`
	MaxUses int32 `json:"maxUses,omitempty"`
	MaxUsesPerCustomer int32 `json:"maxUsesPerCustomer,omitempty"`
	MinOrderAmount string `json:"minOrderAmount,omitempty"`
	ProductIds interface{} `json:"productIds,omitempty"`
	StartsAt string `json:"startsAt,omitempty"`
}
