// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ConfigFieldKind - ConfigFieldKind struct
type ConfigFieldKind struct {
	Type string `json:"type"`
	Options []string `json:"options"`
}
