// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// LoginRequest - LoginRequest struct
type LoginRequest struct {
	Email string `json:"email"`
	Password string `json:"password"`
	TotpCode string `json:"totp_code,omitempty"`
}
