// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// DeliverableResponse - DeliverableResponse struct
type DeliverableResponse struct {
	AvailableStock int64 `json:"availableStock"`
	DeliverableQuantity int64 `json:"deliverableQuantity"`
	MaxSellable int64 `json:"maxSellable,omitempty"`
	ProductId string `json:"productId"`
	ReservedStock int64 `json:"reservedStock"`
	WarehouseId string `json:"warehouseId,omitempty"`
}
