// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ResetPasswordRequest - ResetPasswordRequest struct
type ResetPasswordRequest struct {
	NewPassword string `json:"new_password"`
	Token string `json:"token"`
}
