// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TrainingAssignmentCreate - TrainingAssignmentCreate struct
type TrainingAssignmentCreate struct {
	AssignedBy string `json:"assignedBy,omitempty"`
	DueDate string `json:"dueDate,omitempty"`
	EmployeeId string `json:"employeeId,omitempty"`
	Notes string `json:"notes,omitempty"`
	Status AssignmentStatus `json:"status,omitempty"`
	TrainingId string `json:"trainingId,omitempty"`
}
