// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PaymentCreate - PaymentCreate struct
type PaymentCreate struct {
	Amount string `json:"amount,omitempty"`
	Attachment interface{} `json:"attachment,omitempty"`
	Currency string `json:"currency,omitempty"`
	CustomerId string `json:"customerId,omitempty"`
	Description string `json:"description,omitempty"`
	Metadata interface{} `json:"metadata,omitempty"`
	Method PaymentMethod `json:"method,omitempty"`
	PaymentDate string `json:"paymentDate,omitempty"`
	Reference string `json:"reference,omitempty"`
}
