// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PostingCategoryType - Posting category type: income or expense.
type PostingCategoryType struct {
}
