// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// StockAdjustment - StockAdjustment struct
type StockAdjustment struct {
	BatchNumber string `json:"batchNumber,omitempty"`
	BinLocation string `json:"binLocation,omitempty"`
	ExpiryDate string `json:"expiryDate,omitempty"`
	ProductId string `json:"productId,omitempty"`
	Quantity int64 `json:"quantity"`
	SerialNumbers []string `json:"serialNumbers,omitempty"`
}
