// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// WorkflowEnabledUpdate - WorkflowEnabledUpdate struct
type WorkflowEnabledUpdate struct {
	Enabled bool `json:"enabled"`
}
