// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ConfigFieldKindOneOf1 - ConfigFieldKindOneOf1 struct
type ConfigFieldKindOneOf1 struct {
	Type string `json:"type"`
}
