// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// EuerZeile - EuerZeile struct
type EuerZeile struct {
	Abschnitt string `json:"abschnitt"`
	Betrag string `json:"betrag"`
	Bezeichnung string `json:"bezeichnung"`
	Zeile int32 `json:"zeile"`
}
