// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TrainingAssignment - TrainingAssignment struct
type TrainingAssignment struct {
	AssignedBy string `json:"assignedBy,omitempty"`
	CreatedAt string `json:"createdAt,omitempty"`
	DeletedAt string `json:"deletedAt,omitempty"`
	DueDate string `json:"dueDate,omitempty"`
	EmployeeId string `json:"employeeId,omitempty"`
	Id string `json:"id,omitempty"`
	Notes string `json:"notes,omitempty"`
	Status AssignmentStatus `json:"status,omitempty"`
	TenantId string `json:"tenantId,omitempty"`
	TrainingId string `json:"trainingId,omitempty"`
	UpdatedAt string `json:"updatedAt,omitempty"`
}
