// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ImportTestResponse - ImportTestResponse struct
type ImportTestResponse struct {
	Error string `json:"error,omitempty"`
	Ok bool `json:"ok"`
}
