// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// RemoveUserRequest - RemoveUserRequest struct
type RemoveUserRequest struct {
	Email string `json:"email"`
}
