// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// BwaRevenue - BwaRevenue struct
type BwaRevenue struct {
	RevenueBreakdown []RevenueItem `json:"revenue_breakdown"`
	TotalRevenue string `json:"total_revenue"`
}
