// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// KostenEintrag - KostenEintrag struct
type KostenEintrag struct {
	Beschreibung string `json:"beschreibung"`
	Betrag string `json:"betrag"`
	Datum string `json:"datum"`
	Typ string `json:"typ"`
}
