// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TrackingInfo - TrackingInfo struct
type TrackingInfo struct {
	Carrier string `json:"carrier"`
	EstimatedDelivery string `json:"estimated_delivery,omitempty"`
	Events []TrackingEvent `json:"events"`
	RawResponse interface{} `json:"raw_response,omitempty"`
	Status string `json:"status"`
	TrackingNumber string `json:"tracking_number"`
}
