// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GewinnverwendungsZeile - GewinnverwendungsZeile struct
type GewinnverwendungsZeile struct {
	Betrag string `json:"betrag"`
	Label string `json:"label"`
}
