// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PublicReturnRequest - PublicReturnRequest struct
type PublicReturnRequest struct {
	Email string `json:"email"`
	Items []PublicReturnItem `json:"items"`
	Notes string `json:"notes,omitempty"`
	OrderNumber string `json:"orderNumber"`
}
