// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// RateResponse - RateResponse struct
type RateResponse struct {
	Rates []ShippingRate `json:"rates"`
}
