// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Budget - Budget struct
type Budget struct {
	Category string `json:"category"`
	MonthlyGoal string `json:"monthlyGoal"`
	UpdatedAt string `json:"updatedAt,omitempty"`
	Year int32 `json:"year"`
}
