// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// StockUpdateRequest - StockUpdateRequest struct
type StockUpdateRequest struct {
	Quantity int64 `json:"quantity"`
}
