// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// UpdateConnectionRequest - UpdateConnectionRequest struct
type UpdateConnectionRequest struct {
	ApiKey string `json:"api_key,omitempty"`
	ApiSecret string `json:"api_secret,omitempty"`
	Config interface{} `json:"config,omitempty"`
	IsActive bool `json:"is_active,omitempty"`
	Label string `json:"label,omitempty"`
	ShopDomain string `json:"shop_domain,omitempty"`
}
