// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CreateEmissionEntry - CreateEmissionEntry struct
type CreateEmissionEntry struct {
	ActivityValue string `json:"activity_value"`
	CategoryId string `json:"category_id"`
	Description string `json:"description"`
	Method string `json:"method"`
	Scope string `json:"scope"`
	Unit string `json:"unit"`
	Year int32 `json:"year"`
}
