// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TrackingEvent - TrackingEvent struct
type TrackingEvent struct {
	Date string `json:"date"`
	Description string `json:"description"`
	Location string `json:"location"`
	Status string `json:"status"`
}
