// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// RecurringTemplate - RecurringTemplate struct
type RecurringTemplate struct {
	CreatedAt string `json:"created_at"`
	DeletedAt string `json:"deleted_at,omitempty"`
	EndDate string `json:"end_date,omitempty"`
	ExecutionInterval string `json:"execution_interval"`
	ExecutionStatus string `json:"execution_status"`
	Finalize bool `json:"finalize"`
	LastExecutedAt string `json:"last_executed_at,omitempty"`
	Name string `json:"name"`
	NextExecutionAt string `json:"next_execution_at,omitempty"`
	StartDate string `json:"start_date"`
	TemplateId string `json:"template_id"`
	TemplateType string `json:"template_type"`
	UpdatedAt string `json:"updated_at,omitempty"`
	VoucherData interface{} `json:"voucher_data"`
}
