// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ReplenishmentResponse - ReplenishmentResponse struct
type ReplenishmentResponse struct {
	GeneratedAt string `json:"generatedAt"`
	Lines []ReplenishmentSuggestionLine `json:"lines"`
	TargetWarehouseId string `json:"targetWarehouseId"`
	TotalSuggestedQuantity int64 `json:"totalSuggestedQuantity"`
}
