// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OpenItem - OpenItem struct
type OpenItem struct {
	AmountDue string `json:"amount_due"`
	AmountPaid string `json:"amount_paid"`
	CustomerId string `json:"customer_id,omitempty"`
	DaysOverdue int64 `json:"days_overdue,omitempty"`
	DueDate string `json:"due_date,omitempty"`
	InvoiceId string `json:"invoice_id"`
	InvoiceNumber string `json:"invoice_number"`
	IssueDate string `json:"issue_date"`
	OpenAmount string `json:"open_amount"`
	ReminderLevel ReminderLevel `json:"reminder_level"`
}
