// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ReorderProposalResponse - The response envelope for a reorder proposal run.
type ReorderProposalResponse struct {
	GeneratedAt string `json:"generatedAt"`
	Lines []ReorderProposalLine `json:"lines"`
	TotalSuggestedQuantity int64 `json:"totalSuggestedQuantity"`
}
