// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ConnectorType - How a marketplace connector authenticates: static API key or OAuth2.
type ConnectorType struct {
}
