// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ActivityStatusUpdate - ActivityStatusUpdate struct
type ActivityStatusUpdate struct {
	Status string `json:"status"`
}
