// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// KonzernStatus - KonzernStatus struct
type KonzernStatus struct {
	Groessenbefreit bool `json:"groessenbefreit"`
	Kapitalmarktorientiert bool `json:"kapitalmarktorientiert"`
	Konzernabschlusspflicht bool `json:"konzernabschlusspflicht"`
	MissingGroupFigures bool `json:"missing_group_figures"`
	Mutterunternehmen bool `json:"mutterunternehmen"`
	ParentName string `json:"parent_name,omitempty"`
	ParentSitus string `json:"parent_situs,omitempty"`
	Participations []KonzernBeteiligung `json:"participations"`
	Thresholds KonzernThresholds `json:"thresholds"`
	Year int32 `json:"year"`
	ZwischenholdingBefreit bool `json:"zwischenholding_befreit"`
	ZwischenholdingHinweis string `json:"zwischenholding_hinweis,omitempty"`
}
