// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// BetriebsstaettenDetail - BetriebsstaettenDetail struct
type BetriebsstaettenDetail struct {
	Beschaefigte int64 `json:"beschaefigte"`
	MonatlicherBeitrag string `json:"monatlicher_beitrag"`
	Name string `json:"name"`
}
