// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// MagicLinkRequest - MagicLinkRequest struct
type MagicLinkRequest struct {
	Email string `json:"email"`
}
