// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// AcceptInviteRequest - AcceptInviteRequest struct
type AcceptInviteRequest struct {
	FirstName string `json:"first_name"`
	LastName string `json:"last_name"`
	Password string `json:"password"`
	PrivacyAccepted bool `json:"privacy_accepted"`
	Token string `json:"token"`
}
