// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OssReport - OssReport struct
type OssReport struct {
	Dependencies []OssDependency `json:"dependencies"`
	TotalCount int32 `json:"total_count"`
}
