// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CommunicationDirection - Direction of the communication relative to the business.
type CommunicationDirection struct {
}
