// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ReplenishmentSuggestionLine - A single replenishment suggestion.
type ReplenishmentSuggestionLine struct {
	CurrentStock int64 `json:"currentStock"`
	MaxStock int64 `json:"maxStock,omitempty"`
	MinStock int64 `json:"minStock,omitempty"`
	ProductId string `json:"productId"`
	ProductName string `json:"productName"`
	Sku string `json:"sku"`
	SourceAvailable int64 `json:"sourceAvailable"`
	SourceWarehouseId string `json:"sourceWarehouseId"`
	SuggestedQuantity int64 `json:"suggestedQuantity"`
	TargetWarehouseId string `json:"targetWarehouseId"`
}
