// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ProductCategoryCreate - ProductCategoryCreate struct
type ProductCategoryCreate struct {
	Description string `json:"description,omitempty"`
	Name string `json:"name"`
	ParentCategoryId string `json:"parentCategoryId,omitempty"`
	SortOrder int32 `json:"sortOrder"`
}
