// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// RfqStatusUpdate - RfqStatusUpdate struct
type RfqStatusUpdate struct {
	Status string `json:"status"`
}
