// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// SyncLog - SyncLog struct
type SyncLog struct {
	CompletedAt string `json:"completed_at,omitempty"`
	ConnectionId string `json:"connection_id"`
	ErrorMessage string `json:"error_message,omitempty"`
	ItemsFailed int32 `json:"items_failed"`
	ItemsSynced int32 `json:"items_synced"`
	LogId string `json:"log_id"`
	Platform string `json:"platform"`
	StartedAt string `json:"started_at"`
	Status string `json:"status"`
	SyncType string `json:"sync_type"`
}
