// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// DpaAcceptRequest - Request body to record DPA acceptance (`PUT /api/v1/gdpr/dpa`).
type DpaAcceptRequest struct {
	AcceptedByName string `json:"acceptedByName"`
	Version string `json:"version"`
}
