// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ProformaInvoice - ProformaInvoice struct
type ProformaInvoice struct {
	ConvertedAt string `json:"convertedAt,omitempty"`
	ConvertedToInvoiceId string `json:"convertedToInvoiceId,omitempty"`
	Currency CurrencyCode `json:"currency"`
	CustomerId string `json:"customerId,omitempty"`
	CustomerSnapshot interface{} `json:"customerSnapshot,omitempty"`
	IssueDate string `json:"issueDate"`
	LineItems interface{} `json:"lineItems"`
	Notes string `json:"notes,omitempty"`
	OrderNumber string `json:"orderNumber,omitempty"`
	PaymentDueDate string `json:"paymentDueDate,omitempty"`
	QuotationId string `json:"quotationId,omitempty"`
	Status ProformaInvoiceStatus `json:"status"`
	Subtotal string `json:"subtotal"`
	TotalAmount string `json:"totalAmount"`
	TotalTax string `json:"totalTax"`
}
