// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// EuerErgebnis - EuerErgebnis struct
type EuerErgebnis struct {
	AnlageZugaenge string `json:"anlage_zugaenge"`
	GewinnVerlust string `json:"gewinn_verlust"`
	Jahr int32 `json:"jahr"`
	SummeAusgaben string `json:"summe_ausgaben"`
	SummeEinnahmen string `json:"summe_einnahmen"`
	Zeilen []EuerZeile `json:"zeilen"`
}
