// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// SendMessageDto - SendMessageDto struct
type SendMessageDto struct {
	Body string `json:"body"`
	IsInternal bool `json:"is_internal,omitempty"`
}
