// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomerInfo - Additional information about the customer placing the shipment.
type CustomerInfo struct {
	AnnualVolume int32 `json:"annual_volume"`
	IsRegistered bool `json:"is_registered"`
}
