// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ApiResponseSubscriptionOverview - ApiResponseSubscriptionOverview struct
type ApiResponseSubscriptionOverview struct {
	Data ApiResponseSubscriptionOverviewData `json:"data,omitempty"`
	Error string `json:"error,omitempty"`
	Message string `json:"message,omitempty"`
	Success bool `json:"success"`
}
