// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// BoxFit - BoxFit struct
type BoxFit struct {
	HeightCm float64 `json:"height_cm"`
	ItemCount int32 `json:"item_count"`
	LengthCm float64 `json:"length_cm"`
	VolumeCm3 float64 `json:"volume_cm3"`
	WidthCm float64 `json:"width_cm"`
}
