// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// SupportTicketUpdate - SupportTicketUpdate struct
type SupportTicketUpdate struct {
	AssignedTo string `json:"assignedTo,omitempty"`
	ChannelId string `json:"channelId,omitempty"`
	ChannelType SupportChannelType `json:"channelType,omitempty"`
	ClosedAt string `json:"closedAt,omitempty"`
	CreatedAt string `json:"createdAt,omitempty"`
	CustomerEmail string `json:"customerEmail,omitempty"`
	CustomerId string `json:"customerId,omitempty"`
	CustomerName string `json:"customerName,omitempty"`
	ExternalId string `json:"externalId,omitempty"`
	FirstMessageAt string `json:"firstMessageAt,omitempty"`
	LastMessageAt string `json:"lastMessageAt,omitempty"`
	LeadId string `json:"leadId,omitempty"`
	MessageCount int32 `json:"messageCount,omitempty"`
	OrderRef string `json:"orderRef,omitempty"`
	Priority TicketPriority `json:"priority,omitempty"`
	Resolution string `json:"resolution,omitempty"`
	Status SupportTicketStatus `json:"status,omitempty"`
	Subject string `json:"subject,omitempty"`
	Tags interface{} `json:"tags,omitempty"`
	TenantId string `json:"tenantId,omitempty"`
	UpdatedAt string `json:"updatedAt,omitempty"`
}
