// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CommunicationChannel - Channel the communication took place on.
type CommunicationChannel struct {
}
