// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Invoice - Invoice struct
type Invoice struct {
	Attachments interface{} `json:"attachments,omitempty"`
	BillingPeriodEnd string `json:"billingPeriodEnd,omitempty"`
	BillingPeriodStart string `json:"billingPeriodStart,omitempty"`
	CancellationDate string `json:"cancellationDate,omitempty"`
	CancellationInvoiceId string `json:"cancellationInvoiceId,omitempty"`
	CancellationReason string `json:"cancellationReason,omitempty"`
	ContractId string `json:"contractId,omitempty"`
	Currency CurrencyCode `json:"currency"`
	CustomerId string `json:"customerId,omitempty"`
	DiscountAmount string `json:"discountAmount,omitempty"`
	DiscountDays int32 `json:"discountDays,omitempty"`
	DiscountPercentage string `json:"discountPercentage,omitempty"`
	DocumentType DocumentType `json:"documentType,omitempty"`
	DunningLevel int32 `json:"dunningLevel,omitempty"`
	InputVatAmount string `json:"inputVatAmount,omitempty"`
	InputVatDeductible bool `json:"inputVatDeductible,omitempty"`
	InputVatPercentage string `json:"inputVatPercentage,omitempty"`
	IntroductionText string `json:"introductionText,omitempty"`
	InvoiceType InvoiceType `json:"invoiceType"`
	IsCancelled bool `json:"isCancelled,omitempty"`
	IsDraft bool `json:"isDraft,omitempty"`
	IsEuAcquisition bool `json:"isEuAcquisition,omitempty"`
	IsEuDelivery bool `json:"isEuDelivery,omitempty"`
	IsIntraCommunityAcquisition bool `json:"isIntraCommunityAcquisition,omitempty"`
	IsReverseCharge bool `json:"isReverseCharge,omitempty"`
	IssueDate string `json:"issueDate"`
	LedgerAccount string `json:"ledgerAccount,omitempty"`
	LineItems interface{} `json:"lineItems"`
	Margin25a bool `json:"margin25a,omitempty"`
	Margin25aGross string `json:"margin25aGross,omitempty"`
	Margin25aPurchasePrice string `json:"margin25aPurchasePrice,omitempty"`
	Notes string `json:"notes,omitempty"`
	OrderNumber string `json:"orderNumber,omitempty"`
	OriginalPdfPath string `json:"originalPdfPath,omitempty"`
	PaidAmount string `json:"paidAmount,omitempty"`
	PaymentDueDate string `json:"paymentDueDate,omitempty"`
	PaymentStatus PaymentStatus `json:"paymentStatus,omitempty"`
	PaymentTermsText string `json:"paymentTermsText,omitempty"`
	PrecedingSalesVoucherId string `json:"precedingSalesVoucherId,omitempty"`
	PrecedingSalesVoucherType PrecedingSalesVoucherType `json:"precedingSalesVoucherType,omitempty"`
	ReceiptConfirmationAvailable bool `json:"receiptConfirmationAvailable,omitempty"`
	RelatedInvoiceId string `json:"relatedInvoiceId,omitempty"`
	RelationshipType string `json:"relationshipType,omitempty"`
	SenderSnapshot interface{} `json:"senderSnapshot,omitempty"`
	SentAt string `json:"sentAt,omitempty"`
	ServicePeriodEnd string `json:"servicePeriodEnd,omitempty"`
	ServicePeriodStart string `json:"servicePeriodStart,omitempty"`
	Status InvoiceStatus `json:"status"`
	Subtotal string `json:"subtotal"`
	SupplierId string `json:"supplierId,omitempty"`
	TaxExemptionReason string `json:"taxExemptionReason,omitempty"`
	TotalAmount string `json:"totalAmount"`
	TotalTax string `json:"totalTax"`
	VatCountry CountryCode `json:"vatCountry,omitempty"`
	VatSpecialCase string `json:"vatSpecialCase,omitempty"`
}
