// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomerCommunication - CustomerCommunication struct
type CustomerCommunication struct {
	Body string `json:"body,omitempty"`
	Channel CommunicationChannel `json:"channel"`
	ContactId string `json:"contactId"`
	Counterparty string `json:"counterparty,omitempty"`
	Direction CommunicationDirection `json:"direction"`
	OccurredAt string `json:"occurredAt,omitempty"`
	Subject string `json:"subject,omitempty"`
	Tags interface{} `json:"tags,omitempty"`
}
