// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ExtraPayment - ExtraPayment struct
type ExtraPayment struct {
	Amount string `json:"amount"`
	EmployeeId string `json:"employee_id"`
	Reason string `json:"reason,omitempty"`
}
