// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TicketMessage - TicketMessage struct
type TicketMessage struct {
	AuthorEmail string `json:"authorEmail,omitempty"`
	AuthorName string `json:"authorName,omitempty"`
	Body string `json:"body"`
	BodyHtml string `json:"bodyHtml,omitempty"`
	ChannelId string `json:"channelId,omitempty"`
	CreatedAt string `json:"createdAt"`
	Direction MessageDirection `json:"direction"`
	ExternalId string `json:"externalId,omitempty"`
	IsInternal bool `json:"isInternal"`
	MessageType MessageType `json:"messageType"`
	Metadata interface{} `json:"metadata"`
	TenantId string `json:"tenantId"`
	TicketId string `json:"ticketId"`
}
