// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PluginErrorOneOf6 - PluginErrorOneOf6 struct
type PluginErrorOneOf6 struct {
	NotImplemented string `json:"NotImplemented"`
}
