// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PriceTierUpdate - PriceTierUpdate struct
type PriceTierUpdate struct {
	CustomerGroupId string `json:"customerGroupId,omitempty"`
	MinQuantity int64 `json:"minQuantity,omitempty"`
	ProductId string `json:"productId,omitempty"`
	UnitPrice string `json:"unitPrice"`
}
