// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// QuotaOverrideFeatures - QuotaOverrideFeatures struct
type QuotaOverrideFeatures struct {
	Erp bool `json:"erp,omitempty"`
	FancyReports bool `json:"fancy_reports,omitempty"`
	TaxAutomations bool `json:"tax_automations,omitempty"`
}
