// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ConfigFieldKindOneOf2 - ConfigFieldKindOneOf2 struct
type ConfigFieldKindOneOf2 struct {
	Type string `json:"type"`
}
