// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ProformaInvoiceStatus - Lifecycle status of a proforma invoice.
type ProformaInvoiceStatus struct {
}
