// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// UserProfile - UserProfile struct
type UserProfile struct {
	CreatedAt string `json:"created_at"`
	Email string `json:"email"`
	EmailVerified bool `json:"email_verified"`
	FirstName string `json:"first_name"`
	FullName string `json:"full_name"`
	Id string `json:"id"`
	LastName string `json:"last_name"`
}
