// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// QuartileBand - QuartileBand struct
type QuartileBand struct {
	FemaleSharePct float64 `json:"female_share_pct"`
	HourlyMedian string `json:"hourly_median"`
	MaleSharePct float64 `json:"male_share_pct"`
	Quartile string `json:"quartile"`
}
