// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// QrCodeResponse - QrCodeResponse struct
type QrCodeResponse struct {
	ContentType string `json:"content_type"`
	QrCodeBase64 string `json:"qr_code_base64"`
}
