// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GewinnverwendungsExportResponse - GewinnverwendungsExportResponse struct
type GewinnverwendungsExportResponse struct {
	CsvContent string `json:"csv_content"`
	Filename string `json:"filename"`
}
