// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// JobApplication - JobApplication struct
type JobApplication struct {
	CvFile string `json:"cvFile,omitempty"`
	CvText string `json:"cvText,omitempty"`
	Email string `json:"email,omitempty"`
	MatchReason string `json:"matchReason,omitempty"`
	MatchScore int32 `json:"matchScore,omitempty"`
	Name string `json:"name,omitempty"`
	Phone string `json:"phone,omitempty"`
	PostingId string `json:"postingId,omitempty"`
	Source string `json:"source"`
	Status ApplicationStatus `json:"status"`
}
