// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ConvertResponse - Response of the proforma → invoice conversion.
type ConvertResponse struct {
	InvoiceId string `json:"invoiceId"`
	InvoiceNumber string `json:"invoiceNumber"`
	ProformaId string `json:"proformaId"`
	ProformaNumber string `json:"proformaNumber"`
}
