// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// SupportChannel - SupportChannel struct
type SupportChannel struct {
	ChannelType SupportChannelType `json:"channelType"`
	Config interface{} `json:"config"`
	CreatedAt string `json:"createdAt"`
	IsActive bool `json:"isActive"`
	Name string `json:"name"`
	TenantId string `json:"tenantId"`
	UpdatedAt string `json:"updatedAt,omitempty"`
}
