// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// AnlageSErgebnis - AnlageSErgebnis struct
type AnlageSErgebnis struct {
	GewinnVerlust string `json:"gewinn_verlust"`
	Jahr int32 `json:"jahr"`
	KfzHinweise []AnlageSKfzHinweis `json:"kfz_hinweise"`
}
