// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PurchaseOrderStatusUpdate - PurchaseOrderStatusUpdate struct
type PurchaseOrderStatusUpdate struct {
	Status string `json:"status"`
}
