// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// InviteRequest - InviteRequest struct
type InviteRequest struct {
	Email string `json:"email"`
}
