// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// JobPosting - JobPosting struct
type JobPosting struct {
	Currency string `json:"currency,omitempty"`
	Department string `json:"department,omitempty"`
	Description string `json:"description"`
	EmploymentType EmploymentType `json:"employmentType,omitempty"`
	Location string `json:"location,omitempty"`
	Remote bool `json:"remote"`
	RequiredSkills interface{} `json:"requiredSkills"`
	Requirements string `json:"requirements,omitempty"`
	SalaryMax int32 `json:"salaryMax,omitempty"`
	SalaryMin int32 `json:"salaryMin,omitempty"`
	Status JobPostingStatus `json:"status"`
	Title string `json:"title"`
}
