// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// MessageDirection - Message direction relative to the business.
type MessageDirection struct {
}
