// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// JobPostingFilter - JobPostingFilter struct
type JobPostingFilter struct {
	Page int32 `json:"page,omitempty"`
	PageSize int32 `json:"pageSize,omitempty"`
	Status string `json:"status,omitempty"`
}
