// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// VerifyEmailRequest - VerifyEmailRequest struct
type VerifyEmailRequest struct {
	Token string `json:"token"`
}
