// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// DatevImportResponse - DatevImportResponse struct
type DatevImportResponse struct {
	Count int32 `json:"count"`
	Filename string `json:"filename"`
	Rows []DatevImportRow `json:"rows"`
}
