// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ContactHistoryResponse - Aggregated history for a single contact: all communications plus a lightweight per-channel breakdown.
type ContactHistoryResponse struct {
	ContactId string `json:"contactId"`
	InboundCount int64 `json:"inboundCount"`
	Items []CustomerCommunication `json:"items"`
	OutboundCount int64 `json:"outboundCount"`
}
