// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Workflow - Workflow struct
type Workflow struct {
	Actions interface{} `json:"actions,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
	Name string `json:"name"`
	TriggerEvent string `json:"triggerEvent"`
}
