// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// JobPostingUpdate - JobPostingUpdate struct
type JobPostingUpdate struct {
	Currency string `json:"currency,omitempty"`
	Department string `json:"department,omitempty"`
	Description string `json:"description,omitempty"`
	EmploymentType EmploymentType `json:"employmentType,omitempty"`
	Location string `json:"location,omitempty"`
	Remote bool `json:"remote,omitempty"`
	RequiredSkills interface{} `json:"requiredSkills,omitempty"`
	Requirements string `json:"requirements,omitempty"`
	SalaryMax int32 `json:"salaryMax,omitempty"`
	SalaryMin int32 `json:"salaryMin,omitempty"`
	Status JobPostingStatus `json:"status,omitempty"`
	Title string `json:"title,omitempty"`
}
