// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PackingQueue - PackingQueue struct
type PackingQueue struct {
	Items []PackingQueueItem `json:"items"`
	Page int32 `json:"page"`
	PageSize int32 `json:"page_size"`
	TotalCount int64 `json:"total_count"`
}
