// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PayrollAutopayPayload - PayrollAutopayPayload struct
type PayrollAutopayPayload struct {
	DebtorBic string `json:"debtor_bic,omitempty"`
	DebtorIban string `json:"debtor_iban,omitempty"`
	DebtorName string `json:"debtor_name,omitempty"`
	ExecutionDate string `json:"execution_date,omitempty"`
}
