// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Employee - Employee struct
type Employee struct {
	Address string `json:"address,omitempty"`
	BackupEmployeeId string `json:"backupEmployeeId,omitempty"`
	Bic string `json:"bic,omitempty"`
	City string `json:"city,omitempty"`
	Country CountryCode `json:"country,omitempty"`
	CreatedAt string `json:"createdAt,omitempty"`
	DateOfBirth string `json:"dateOfBirth,omitempty"`
	DeletedAt string `json:"deletedAt,omitempty"`
	DepartmentId string `json:"departmentId,omitempty"`
	Email string `json:"email,omitempty"`
	FirstName string `json:"firstName,omitempty"`
	Gender Gender `json:"gender,omitempty"`
	HireDate string `json:"hireDate,omitempty"`
	HourlyCost string `json:"hourlyCost,omitempty"`
	Iban string `json:"iban,omitempty"`
	Id string `json:"id,omitempty"`
	JobTitle string `json:"jobTitle,omitempty"`
	LastLogin string `json:"lastLogin,omitempty"`
	LastName string `json:"lastName,omitempty"`
	LastUpdated string `json:"lastUpdated,omitempty"`
	MonthlySalary string `json:"monthlySalary,omitempty"`
	Phone string `json:"phone,omitempty" validate:"regexp=^\\+?[0-9\\s\\-\\(\\)]{7\\,20}$"`
	State string `json:"state,omitempty"`
	Status EmployeeStatus `json:"status,omitempty"`
	TenantId string `json:"tenantId,omitempty"`
	UpdatedAt string `json:"updatedAt,omitempty"`
	UserId string `json:"userId,omitempty"`
	WeeklyHours string `json:"weeklyHours,omitempty"`
	Zip string `json:"zip,omitempty"`
}
