// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ReturnOrderStatusUpdate - ReturnOrderStatusUpdate struct
type ReturnOrderStatusUpdate struct {
	Status string `json:"status"`
}
