// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// BudgetErgebnis - BudgetErgebnis struct
type BudgetErgebnis struct {
	Jahr int32 `json:"jahr"`
	Monat int32 `json:"monat"`
	MonatsBudget []BudgetKategorie `json:"monats_budget"`
	PrognoseRestjahr []BudgetKategorie `json:"prognose_restjahr"`
}
