// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OAuthAuthorizeRequest - OAuthAuthorizeRequest struct
type OAuthAuthorizeRequest struct {
	Config interface{} `json:"config,omitempty"`
	Platform string `json:"platform"`
	RedirectUri string `json:"redirect_uri"`
}
