// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// UpsCredentials - UpsCredentials struct
type UpsCredentials struct {
	ClientId string `json:"client_id"`
	ClientSecret string `json:"client_secret"`
	ShipperNumber string `json:"shipper_number,omitempty"`
}
