// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// YearTotal - YearTotal struct
type YearTotal struct {
	Tco2e string `json:"tco2e"`
	Year int32 `json:"year"`
}
