// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ShippingRate - ShippingRate struct
type ShippingRate struct {
	Breakdown string `json:"breakdown,omitempty"`
	Carrier string `json:"carrier"`
	CrossBorderSurcharge string `json:"cross_border_surcharge,omitempty"`
	DestinationCountry string `json:"destination_country"`
	EstimatedDays int32 `json:"estimated_days,omitempty"`
	FromApi bool `json:"from_api"`
	InsuredValue string `json:"insured_value,omitempty"`
	IslandSurcharge string `json:"island_surcharge,omitempty"`
	OriginCountry string `json:"origin_country"`
	Rate string `json:"rate"`
	Service string `json:"service"`
	VolumeDiscount string `json:"volume_discount,omitempty"`
	WeightKg float64 `json:"weight_kg"`
}
