// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ProductionOrderCosting - Actual-costing (Nachkalkulation) report for a production order.
type ProductionOrderCosting struct {
	CostPerUnit string `json:"costPerUnit"`
	CostSource string `json:"costSource"`
	Lines []CostingLine `json:"lines"`
	MarginPerUnit string `json:"marginPerUnit,omitempty"`
	MarginPercent string `json:"marginPercent,omitempty"`
	MaterialCostTotal string `json:"materialCostTotal"`
	OrderNumber string `json:"orderNumber"`
	ProductionOrderId string `json:"productionOrderId"`
	Quantity int64 `json:"quantity"`
	SalePrice string `json:"salePrice,omitempty"`
	Status string `json:"status"`
}
