// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Address - Address struct
type Address struct {
	City string `json:"city"`
	Company string `json:"company,omitempty"`
	Country string `json:"country"`
	Email string `json:"email,omitempty"`
	Name string `json:"name"`
	Phone string `json:"phone,omitempty"`
	Street string `json:"street"`
	StreetNumber string `json:"street_number"`
	Zip string `json:"zip"`
}
