// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ScopeTotal - ScopeTotal struct
type ScopeTotal struct {
	Scope string `json:"scope"`
	Tco2e string `json:"tco2e"`
}
