// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// AbsenceUpdate - AbsenceUpdate struct
type AbsenceUpdate struct {
	AbsenceType AbsenceType `json:"absenceType,omitempty"`
	ApprovedAt string `json:"approvedAt,omitempty"`
	ApprovedBy string `json:"approvedBy,omitempty"`
	EmployeeId string `json:"employeeId,omitempty"`
	EndDate string `json:"endDate,omitempty"`
	Notes string `json:"notes,omitempty"`
	StartDate string `json:"startDate,omitempty"`
	Status AbsenceStatus `json:"status,omitempty"`
}
