// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CategoryTotal - CategoryTotal struct
type CategoryTotal struct {
	CategoryId string `json:"category_id"`
	SharePct float64 `json:"share_pct"`
	Tco2e string `json:"tco2e"`
}
