// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PluginErrorOneOf - PluginErrorOneOf struct
type PluginErrorOneOf struct {
	BadRequest []map[string]interface{} `json:"BadRequest"`
}
