// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// InventoryCountStatusUpdate - InventoryCountStatusUpdate struct
type InventoryCountStatusUpdate struct {
	Status string `json:"status"`
}
