// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PayrollPayPayload - PayrollPayPayload struct
type PayrollPayPayload struct {
	PaymentDate string `json:"payment_date"`
}
