// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// EmissionEntry - EmissionEntry struct
type EmissionEntry struct {
	ActivityValue string `json:"activityValue"`
	CategoryId string `json:"categoryId"`
	Description string `json:"description"`
	EfSource string `json:"efSource"`
	EfVersion string `json:"efVersion"`
	Method EmissionMethod `json:"method"`
	Scope GhgScope `json:"scope"`
	Tco2e string `json:"tco2e"`
	Unit string `json:"unit"`
	UpdatedAt string `json:"updatedAt,omitempty"`
	Year int32 `json:"year"`
}
