// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// StockTransferStatusUpdate - StockTransferStatusUpdate struct
type StockTransferStatusUpdate struct {
	Status string `json:"status"`
}
