// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CreateChannelDto - CreateChannelDto struct
type CreateChannelDto struct {
	ChannelType string `json:"channel_type"`
	Config interface{} `json:"config"`
	Name string `json:"name"`
}
