// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CostingLine - A single costing line: material cost for one BOM component.
type CostingLine struct {
	LineCost string `json:"lineCost"`
	Name string `json:"name"`
	ProductId string `json:"productId"`
	QuantityPerUnit int64 `json:"quantityPerUnit"`
	Sku string `json:"sku"`
	TotalQuantity int64 `json:"totalQuantity"`
	UnitPurchasePrice string `json:"unitPurchasePrice,omitempty"`
}
