// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TenantSettings - TenantSettings struct
type TenantSettings struct {
	CompanyType CompanyType `json:"companyType"`
	DpaAcceptedAt string `json:"dpaAcceptedAt,omitempty"`
	DpaAcceptedBy string `json:"dpaAcceptedBy,omitempty"`
	DpaVersion string `json:"dpaVersion,omitempty"`
	Features interface{} `json:"features"`
}
