// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// SmtpConfig - SmtpConfig struct
type SmtpConfig struct {
	Encryption SmtpEncryption `json:"encryption"`
	FromAddress string `json:"from_address"`
	FromName string `json:"from_name,omitempty"`
	Host string `json:"host"`
	Password string `json:"password"`
	Port int32 `json:"port"`
	TimeoutSeconds int64 `json:"timeout_seconds,omitempty"`
	Username string `json:"username"`
}
