// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// RevenueItem - RevenueItem struct
type RevenueItem struct {
	Amount string `json:"amount"`
	Category string `json:"category"`
	Percentage float64 `json:"percentage"`
}
