// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PlanLimits - Per-plan numeric limits. `-1` in any field means unlimited.
type PlanLimits struct {
	MaxConnectors int32 `json:"maxConnectors"`
	MaxInvoicesPerMonth int64 `json:"maxInvoicesPerMonth"`
	MaxUsers int32 `json:"maxUsers"`
	Metered map[string]int64 `json:"metered,omitempty"`
	PaidConnectors []string `json:"paidConnectors"`
}
