// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// EventSubscription - EventSubscription struct
type EventSubscription struct {
	CallbackUrl string `json:"callback_url"`
	EventType string `json:"event_type"`
	IsActive bool `json:"is_active"`
	SubscriptionId string `json:"subscription_id"`
}
