// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PaymentGatewayCreate - PaymentGatewayCreate struct
type PaymentGatewayCreate struct {
	Config interface{} `json:"config"`
	CreatedAt string `json:"createdAt"`
	DeletedAt string `json:"deletedAt,omitempty"`
	Enabled bool `json:"enabled"`
	GatewayType GatewayType `json:"gatewayType"`
	Label string `json:"label"`
	UpdatedAt string `json:"updatedAt,omitempty"`
}
