// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PublicPosting - Minimal shape for the public careers page (no tenant internals).
type PublicPosting struct {
	Currency string `json:"currency,omitempty"`
	Description string `json:"description"`
	EmploymentType string `json:"employmentType,omitempty"`
	Id string `json:"id"`
	Location string `json:"location,omitempty"`
	Remote bool `json:"remote"`
	RequiredSkills []string `json:"requiredSkills"`
	Requirements string `json:"requirements,omitempty"`
	SalaryMax int32 `json:"salaryMax,omitempty"`
	SalaryMin int32 `json:"salaryMin,omitempty"`
	Title string `json:"title"`
}
