// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ReturnWarehouseSummary - Aggregation for a single warehouse.
type ReturnWarehouseSummary struct {
	ItemsRestocked int64 `json:"itemsRestocked"`
	ItemsScrapped int64 `json:"itemsScrapped"`
	Returns int64 `json:"returns"`
	WarehouseId string `json:"warehouseId,omitempty"`
}
