// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// VatItem - VatItem struct
type VatItem struct {
	NetAmount string `json:"net_amount"`
	TaxAmount string `json:"tax_amount"`
	TaxRate string `json:"tax_rate"`
}
