// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// QuotaOverride - Schema of the `tenants.quotas` JSON override column. Any field that is present overrides the plan-derived value.
type QuotaOverride struct {
	Features QuotaOverrideFeatures `json:"features,omitempty"`
	MaxConnectors int32 `json:"max_connectors,omitempty"`
	MaxInvoicesPerMonth int64 `json:"max_invoices_per_month,omitempty"`
	MaxUsers int32 `json:"max_users,omitempty"`
	Metered map[string]int64 `json:"metered,omitempty"`
	Plan string `json:"plan,omitempty"`
}
