// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GewinnverwendungsReport - GewinnverwendungsReport struct
type GewinnverwendungsReport struct {
	Bilanzgewinn string `json:"bilanzgewinn"`
	GesetzlicheRuecklageBestand string `json:"gesetzliche_ruecklage_bestand"`
	GesetzlicheRuecklageCap string `json:"gesetzliche_ruecklage_cap"`
	GesetzlicheRuecklageNach string `json:"gesetzliche_ruecklage_nach"`
	GesetzlicheRuecklageSoll string `json:"gesetzliche_ruecklage_soll"`
	GezeichnetesKapital string `json:"gezeichnetes_kapital"`
	Jahresueberschuss string `json:"jahresueberschuss"`
	Year int32 `json:"year"`
	Zeilen []GewinnverwendungsZeile `json:"zeilen"`
}
