// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// UpdateRolePayload - UpdateRolePayload struct
type UpdateRolePayload struct {
	Role string `json:"role"`
	SyncPermissions bool `json:"sync_permissions,omitempty"`
}
