// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// InvoiceLineItem - InvoiceLineItem struct
type InvoiceLineItem struct {
	ArticleNumber string `json:"article_number,omitempty"`
	Description string `json:"description"`
	DiscountAmount string `json:"discount_amount,omitempty"`
	DiscountPercentage string `json:"discount_percentage,omitempty"`
	InputVatDeductible bool `json:"input_vat_deductible,omitempty"`
	InputVatRate string `json:"input_vat_rate,omitempty"`
	IsIntraCommunityAcquisition bool `json:"is_intra_community_acquisition,omitempty"`
	IsMargin25a bool `json:"is_margin_25a,omitempty"`
	LedgerAccount string `json:"ledger_account,omitempty"`
	LineTotal string `json:"line_total"`
	LineTotalGross string `json:"line_total_gross,omitempty"`
	Margin25aPurchasePrice string `json:"margin_25a_purchase_price,omitempty"`
	MeterPointId string `json:"meter_point_id,omitempty"`
	Position int64 `json:"position"`
	PriceComponents interface{} `json:"price_components,omitempty"`
	ProductId string `json:"product_id,omitempty"`
	ProductSku string `json:"product_sku,omitempty"`
	Quantity string `json:"quantity"`
	SupplierArticleNumber string `json:"supplier_article_number,omitempty"`
	TaxRate string `json:"tax_rate,omitempty"`
	Unit interface{} `json:"unit"`
	UnitPrice string `json:"unit_price"`
	UsageDataId string `json:"usage_data_id,omitempty"`
	VatRateNominal string `json:"vat_rate_nominal,omitempty"`
	VatSpecialCase string `json:"vat_special_case,omitempty"`
}
