// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PosRegisterCreate - PosRegisterCreate struct
type PosRegisterCreate struct {
	Name string `json:"name"`
	Status PosRegisterStatus `json:"status,omitempty"`
}
