// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// AiConfigDto - AiConfigDto struct
type AiConfigDto struct {
	AutoReply bool `json:"auto_reply,omitempty"`
	MaxToolCalls int32 `json:"max_tool_calls,omitempty"`
	Model string `json:"model"`
	Name string `json:"name"`
	Provider string `json:"provider"`
	SystemPrompt string `json:"system_prompt,omitempty"`
	TriggerOn []string `json:"trigger_on,omitempty"`
}
