// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// EmissionMethod - Emission calculation method: \"activity\" | \"spend\" | \"supplier\".
type EmissionMethod struct {
}
