// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PublicDeliveryAppointmentRequest - PublicDeliveryAppointmentRequest struct
type PublicDeliveryAppointmentRequest struct {
	Email string `json:"email"`
	Notes string `json:"notes,omitempty"`
	RequestedDate string `json:"requestedDate"`
	SupplierName string `json:"supplierName"`
	TimeSlot string `json:"timeSlot,omitempty"`
	WarehouseCode string `json:"warehouseCode"`
}
