// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PluginErrorOneOf3 - PluginErrorOneOf3 struct
type PluginErrorOneOf3 struct {
	InternalError []map[string]interface{} `json:"InternalError"`
}
