// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// RfqUpdate - RfqUpdate struct
type RfqUpdate struct {
	Currency string `json:"currency,omitempty"`
	LineItems interface{} `json:"lineItems,omitempty"`
	Notes string `json:"notes,omitempty"`
	RequestedDate string `json:"requestedDate,omitempty"`
	ResponseDate string `json:"responseDate,omitempty"`
	RfqNumber string `json:"rfqNumber,omitempty"`
	Status RfqStatus `json:"status,omitempty"`
	SupplierContactId string `json:"supplierContactId,omitempty"`
	SupplierName string `json:"supplierName,omitempty"`
}
