// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PublicReturnResponse - PublicReturnResponse struct
type PublicReturnResponse struct {
	CreatedAt string `json:"createdAt"`
	Items interface{} `json:"items"`
	Notes string `json:"notes,omitempty"`
	OrderNumber string `json:"orderNumber,omitempty"`
	ReturnNumber string `json:"returnNumber"`
	ReturnOrderId string `json:"returnOrderId"`
	Status string `json:"status"`
	UpdatedAt string `json:"updatedAt,omitempty"`
}
