// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ReorderProposalLine - A single reorder proposal line.
type ReorderProposalLine struct {
	CurrentStock int64 `json:"currentStock"`
	MaxStock int64 `json:"maxStock,omitempty"`
	MinStock int64 `json:"minStock,omitempty"`
	ProductId string `json:"productId"`
	ProductName string `json:"productName"`
	ReorderQuantity int64 `json:"reorderQuantity,omitempty"`
	Sku string `json:"sku"`
	SuggestedQuantity int64 `json:"suggestedQuantity"`
}
