// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PublicDeliveryAppointmentStatusResponse - PublicDeliveryAppointmentStatusResponse struct
type PublicDeliveryAppointmentStatusResponse struct {
	AppointmentId string `json:"appointmentId"`
	RequestedDate string `json:"requestedDate"`
	Status string `json:"status"`
	TimeSlot string `json:"timeSlot,omitempty"`
	WarehouseName string `json:"warehouseName"`
}
