// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CreateShipmentRequest - CreateShipmentRequest struct
type CreateShipmentRequest struct {
	Carrier string `json:"carrier"`
	Service string `json:"service,omitempty"`
	WeightKg float64 `json:"weight_kg,omitempty"`
}
