// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ShippingCredentials - Per-tenant credentials for real shipping provider APIs (stored in the `shipping` key of the settings JSON blob). Auth is either OAuth client credentials (UPS) or a user-supplied API key (DHL).
type ShippingCredentials struct {
	Dhl DhlCredentials `json:"dhl,omitempty"`
	Ups UpsCredentials `json:"ups,omitempty"`
}
