// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PrecedingSalesVoucherType - Type of the sales voucher that preceded this document.
type PrecedingSalesVoucherType struct {
}
