// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomerCreate - CustomerCreate struct
type CustomerCreate struct {
	Address interface{} `json:"address,omitempty"`
	ContactPerson string `json:"contactPerson,omitempty"`
	Email string `json:"email,omitempty"`
	ExternalOrderNumber string `json:"externalOrderNumber,omitempty"`
	Name string `json:"name"`
	PaymentGracePeriodDays int32 `json:"paymentGracePeriodDays,omitempty"`
	Phone string `json:"phone,omitempty" validate:"regexp=^\\+?[0-9\\s\\-\\(\\)]{7\\,20}$"`
	VatId string `json:"vatId,omitempty" validate:"regexp=^[A-Z]{2}[0-9A-Z]{8\\,15}$"`
}
