// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TenantUser - TenantUser struct
type TenantUser struct {
	Email string `json:"email"`
	EmailVerified bool `json:"email_verified"`
	IsActive bool `json:"is_active"`
	JoinedAt string `json:"joined_at"`
	LastLogin string `json:"last_login,omitempty"`
	Name string `json:"name"`
	Permissions []string `json:"permissions"`
	Role string `json:"role"`
	UserId string `json:"user_id"`
}
