// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ApplicationFilter - ApplicationFilter struct
type ApplicationFilter struct {
	Page int32 `json:"page,omitempty"`
	PageSize int32 `json:"pageSize,omitempty"`
	PostingId string `json:"postingId,omitempty"`
	Status string `json:"status,omitempty"`
}
