// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GenerateVariantsRequest - Request body for generating the full variant set from option values.
type GenerateVariantsRequest struct {
	Options map[string][]string `json:"options,omitempty"`
	PriceDelta string `json:"priceDelta,omitempty"`
	ProductId string `json:"productId"`
	SkuPrefix string `json:"skuPrefix,omitempty"`
}
