// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// NotificationDto - Wire shape of a notification row (mirrors frontend Notification type).
type NotificationDto struct {
	CreatedAt string `json:"created_at"`
	Id string `json:"id"`
	IsRead bool `json:"is_read"`
	Message string `json:"message,omitempty"`
	SentViaEmail bool `json:"sent_via_email"`
	TenantId string `json:"tenant_id"`
	Title string `json:"title"`
	UserId string `json:"user_id"`
}
