// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// UpdateProfileRequest - UpdateProfileRequest struct
type UpdateProfileRequest struct {
	AvatarUrl string `json:"avatar_url,omitempty"`
	FirstName string `json:"first_name,omitempty"`
	LastName string `json:"last_name,omitempty"`
	Name string `json:"name,omitempty"`
}
