// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// InstituteProfile - InstituteProfile struct
type InstituteProfile struct {
	InstituteType InstituteType `json:"instituteType,omitempty"`
	Kapitalmarktorientiert bool `json:"kapitalmarktorientiert,omitempty"`
}
