// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// MirrorTriggerResponse - MirrorTriggerResponse struct
type MirrorTriggerResponse struct {
	JobId string `json:"job_id"`
}
