// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// MarketplaceSyncLog - MarketplaceSyncLog struct
type MarketplaceSyncLog struct {
	CompletedAt string `json:"completedAt,omitempty"`
	ConnectionId string `json:"connectionId"`
	ErrorMessage string `json:"errorMessage,omitempty"`
	ItemsFailed int32 `json:"itemsFailed"`
	ItemsSynced int32 `json:"itemsSynced"`
	Platform string `json:"platform"`
	StartedAt string `json:"startedAt"`
	Status SyncLogStatus `json:"status"`
	SyncType SyncType `json:"syncType"`
}
