// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TotpSetupResponse - TotpSetupResponse struct
type TotpSetupResponse struct {
	BackupCodes []string `json:"backup_codes"`
	QrCodeUrl string `json:"qr_code_url"`
	Secret string `json:"secret"`
}
