// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// MagicLinkVerifyRequest - MagicLinkVerifyRequest struct
type MagicLinkVerifyRequest struct {
	Token string `json:"token"`
}
