// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OrderTagsRequest - OrderTagsRequest struct
type OrderTagsRequest struct {
	Tags []string `json:"tags"`
}
