// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// MeteredUsage - MeteredUsage struct
type MeteredUsage struct {
	Limit int64 `json:"limit"`
	Meter string `json:"meter"`
	Used int64 `json:"used"`
}
