// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PluginPricingOneOf2 - PluginPricingOneOf2 struct
type PluginPricingOneOf2 struct {
	PricePerMonth float64 `json:"price_per_month"`
	Type string `json:"type"`
}
