// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// WarehouseStock - WarehouseStock struct
type WarehouseStock struct {
	BatchNumber string `json:"batchNumber,omitempty"`
	BinLocation string `json:"binLocation,omitempty"`
	ExpiryDate string `json:"expiryDate,omitempty"`
	ProductId string `json:"productId"`
	Quantity int64 `json:"quantity"`
	SerialNumbers interface{} `json:"serialNumbers,omitempty"`
	WarehouseId string `json:"warehouseId"`
}
