// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PayGapInfoResponse - PayGapInfoResponse struct
type PayGapInfoResponse struct {
	EmployeeId string `json:"employee_id"`
	FirstName string `json:"first_name"`
	Gender string `json:"gender,omitempty"`
	GroupMedianHourly float64 `json:"group_median_hourly,omitempty"`
	GroupMedianMonthly float64 `json:"group_median_monthly,omitempty"`
	GroupSize int32 `json:"group_size"`
	JobTitle string `json:"job_title"`
	LastName string `json:"last_name"`
	OverallMedianHourly float64 `json:"overall_median_hourly,omitempty"`
	OwnHourlyGross float64 `json:"own_hourly_gross,omitempty"`
	OwnMonthlyGross float64 `json:"own_monthly_gross,omitempty"`
}
