// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CreateEmissionTarget - CreateEmissionTarget struct
type CreateEmissionTarget struct {
	BaseValue string `json:"base_value"`
	BaseYear int32 `json:"base_year"`
	Description string `json:"description"`
	Scope string `json:"scope"`
	TargetValue string `json:"target_value"`
	TargetYear int32 `json:"target_year"`
}
