// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ContactInfo - ContactInfo struct
type ContactInfo struct {
	Hint string `json:"hint"`
	HintEn string `json:"hintEn"`
	Role string `json:"role"`
	RoleEn string `json:"roleEn"`
}
