// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// DpaStatus - DPA acceptance status of the tenant.
type DpaStatus struct {
	Accepted bool `json:"accepted"`
	AcceptedAt string `json:"acceptedAt,omitempty"`
	AcceptedBy string `json:"acceptedBy,omitempty"`
	Version string `json:"version,omitempty"`
}
