// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// EmailTemplate - EmailTemplate struct
type EmailTemplate struct {
	Body string `json:"body"`
	Name string `json:"name"`
	Status EmailTemplateStatus `json:"status"`
	Subject string `json:"subject"`
	Variables interface{} `json:"variables,omitempty"`
}
