// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GatewayOAuthAuthorizeResponse - GatewayOAuthAuthorizeResponse struct
type GatewayOAuthAuthorizeResponse struct {
	AuthorizationUrl string `json:"authorization_url"`
	State string `json:"state"`
}
