// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomerGroupUpdate - CustomerGroupUpdate struct
type CustomerGroupUpdate struct {
	Description string `json:"description,omitempty"`
	MemberIds []string `json:"memberIds,omitempty"`
	MembershipFilter string `json:"membershipFilter,omitempty"`
	Name string `json:"name,omitempty"`
}
