// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PluginErrorOneOf1 - PluginErrorOneOf1 struct
type PluginErrorOneOf1 struct {
	NotFound []map[string]interface{} `json:"NotFound"`
}
