// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// LegalDocument - LegalDocument struct
type LegalDocument struct {
	Content string `json:"content"`
	DocType LegalDocType `json:"docType"`
	Lang LanguageCode `json:"lang"`
	Title string `json:"title"`
}
