// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// BwaExpenses - BwaExpenses struct
type BwaExpenses struct {
	ExpenseBreakdown []ExpenseItem `json:"expense_breakdown"`
	TotalExpenses string `json:"total_expenses"`
}
