// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PaymentGateway - PaymentGateway struct
type PaymentGateway struct {
	Config interface{} `json:"config"`
	CreatedAt string `json:"createdAt"`
	DeletedAt string `json:"deletedAt,omitempty"`
	Enabled bool `json:"enabled"`
	GatewayId string `json:"gatewayId"`
	GatewayType GatewayType `json:"gatewayType"`
	Label string `json:"label"`
	TenantId string `json:"tenantId"`
	UpdatedAt string `json:"updatedAt,omitempty"`
}
