// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OrderUpdate - OrderUpdate struct
type OrderUpdate struct {
	AuditLog interface{} `json:"auditLog,omitempty"`
	Currency string `json:"currency,omitempty"`
	CustomerId string `json:"customerId,omitempty"`
	ExternalReference string `json:"externalReference,omitempty"`
	InvoiceAddress interface{} `json:"invoiceAddress,omitempty"`
	Items interface{} `json:"items,omitempty"`
	Language LanguageCode `json:"language,omitempty"`
	OrderStatus OrderStatus `json:"orderStatus,omitempty"`
	PaymentMethod PaymentMethod `json:"paymentMethod,omitempty"`
	ShippingAddress interface{} `json:"shippingAddress,omitempty"`
	ShippingCost string `json:"shippingCost,omitempty"`
	ShippingMethod string `json:"shippingMethod,omitempty"`
	ShippingWeight string `json:"shippingWeight,omitempty"`
	Tags []string `json:"tags,omitempty"`
	TotalCost string `json:"totalCost,omitempty"`
}
