// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// RateRequest - RateRequest struct
type RateRequest struct {
	Customer CustomerInfo `json:"customer,omitempty"`
	Packages []Package `json:"packages"`
	Recipient Address `json:"recipient"`
	Sender Address `json:"sender"`
}
