// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// LegalDocumentReset - Optional filter for `POST /api/v1/legal/documents/reset`; empty body restores every document of the tenant.
type LegalDocumentReset struct {
	DocType string `json:"docType,omitempty"`
	Lang string `json:"lang,omitempty"`
}
