// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// KonzernBeteiligung - KonzernBeteiligung struct
type KonzernBeteiligung struct {
	CompanyName string `json:"company_name"`
	ControlBasis []string `json:"control_basis"`
	Controlled bool `json:"controlled"`
	OwnershipPct string `json:"ownership_pct"`
}
