// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PostingCategoryUpdate - PostingCategoryUpdate struct
type PostingCategoryUpdate struct {
	AccountNumber string `json:"accountNumber,omitempty"`
	AccountNumberSkr03 string `json:"accountNumberSkr03,omitempty"`
	AccountNumberSkr04 string `json:"accountNumberSkr04,omitempty"`
	AccountNumberSkr49 string `json:"accountNumberSkr49,omitempty"`
	CategoryType PostingCategoryType `json:"categoryType,omitempty"`
	CreatedAt string `json:"createdAt,omitempty"`
	DefaultVatRate int32 `json:"defaultVatRate,omitempty"`
	Description string `json:"description,omitempty"`
	EksCategory string `json:"eksCategory,omitempty"`
	EuVatLine int32 `json:"euVatLine,omitempty"`
	InputVatPercentage string `json:"inputVatPercentage,omitempty"`
	IsActive bool `json:"isActive,omitempty"`
	IsSystem bool `json:"isSystem,omitempty"`
	Name string `json:"name,omitempty"`
	SkrVersion string `json:"skrVersion,omitempty"`
	UpdatedAt string `json:"updatedAt,omitempty"`
	UserModifiedSkr03 bool `json:"userModifiedSkr03,omitempty"`
	UserModifiedSkr04 bool `json:"userModifiedSkr04,omitempty"`
}
