// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// EmissionTargetScope - Emission target scope: \"total\" | \"1\" | \"2\" | \"3\".
type EmissionTargetScope struct {
}
