// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// AiSuggestionRequest - AiSuggestionRequest struct
type AiSuggestionRequest struct {
	Instructions string `json:"instructions,omitempty"`
	MessageBody string `json:"message_body,omitempty"`
	TicketId string `json:"ticket_id"`
}
