// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// AttachmentVersionModel is the Terraform model for attachment_version.
type AttachmentVersionModel struct {
}

