// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// ComplianceTrainingModel is the Terraform model for compliance_training.
type ComplianceTrainingModel struct {
}

