// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// CreateSepaDirectDebitModel is the Terraform model for create_sepa_direct_debit.
type CreateSepaDirectDebitModel struct {
}

