// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// CustomerGroupModel is the Terraform model for customer_group.
type CustomerGroupModel struct {
}

