// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// CustomerCommunicationModel is the Terraform model for customer_communication.
type CustomerCommunicationModel struct {
}

