// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// DatevImportModel is the Terraform model for datev_import.
type DatevImportModel struct {
}

