// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// DeliveryNoteModel is the Terraform model for delivery_note.
type DeliveryNoteModel struct {
}

