// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// DeliveryAppointmentModel is the Terraform model for delivery_appointment.
type DeliveryAppointmentModel struct {
}

