// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// DeliveryDateModel is the Terraform model for delivery_date.
type DeliveryDateModel struct {
}

