// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// DownPaymentInvoiceModel is the Terraform model for down_payment_invoice.
type DownPaymentInvoiceModel struct {
}

