// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// EmailTemplateModel is the Terraform model for email_template.
type EmailTemplateModel struct {
}

