// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// EventSubscriptionModel is the Terraform model for event_subscription.
type EventSubscriptionModel struct {
}

