// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// GenerateXrechnungModel is the Terraform model for generate_xrechnung.
type GenerateXrechnungModel struct {
}

