// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// GenerateQrcodeModel is the Terraform model for generate_qrcode.
type GenerateQrcodeModel struct {
}

