// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// GewerbesteuerModel is the Terraform model for gewerbesteuer.
type GewerbesteuerModel struct {
}

