// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// GewinnverwendungModel is the Terraform model for gewinnverwendung.
type GewinnverwendungModel struct {
}

