// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// GoodsReceiptModel is the Terraform model for goods_receipt.
type GoodsReceiptModel struct {
}

