// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// GroupFigureModel is the Terraform model for group_figure.
type GroupFigureModel struct {
}

