// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// ImportRunnerModel is the Terraform model for import_runner.
type ImportRunnerModel struct {
}

