// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// InstituteProfileModel is the Terraform model for institute_profile.
type InstituteProfileModel struct {
}

