// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// InventoryCountModel is the Terraform model for inventory_count.
type InventoryCountModel struct {
}

