// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// InventoryValueModel is the Terraform model for inventory_value.
type InventoryValueModel struct {
}

