// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// JobApplicationModel is the Terraform model for job_application.
type JobApplicationModel struct {
}

