// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// KostenVorschauModel is the Terraform model for kosten_vorschau.
type KostenVorschauModel struct {
}

