// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// LegalDocumentModel is the Terraform model for legal_document.
type LegalDocumentModel struct {
}

