// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// ListOpenItemsModel is the Terraform model for list_open_items.
type ListOpenItemsModel struct {
}

