// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// MarketplaceApiModel is the Terraform model for marketplace_api.
type MarketplaceApiModel struct {
}

