// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// NotificationsModel is the Terraform model for notifications.
type NotificationsModel struct {
}

