// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// OrderConfirmationModel is the Terraform model for order_confirmation.
type OrderConfirmationModel struct {
}

