// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// ParticipationModel is the Terraform model for participation.
type ParticipationModel struct {
}

