// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// PaymentConditionModel is the Terraform model for payment_condition.
type PaymentConditionModel struct {
}

