// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// PaymentGatewayModel is the Terraform model for payment_gateway.
type PaymentGatewayModel struct {
}

