// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// PlausibilityModel is the Terraform model for plausibility.
type PlausibilityModel struct {
}

