// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// PostingCategoryModel is the Terraform model for posting_category.
type PostingCategoryModel struct {
}

