// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// ProductAttributeModel is the Terraform model for product_attribute.
type ProductAttributeModel struct {
}

