// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// ProductionOrderModel is the Terraform model for production_order.
type ProductionOrderModel struct {
}

