// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// ProductCategoryModel is the Terraform model for product_category.
type ProductCategoryModel struct {
}

