// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// ProductVariantModel is the Terraform model for product_variant.
type ProductVariantModel struct {
}

