// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// ProformaInvoiceModel is the Terraform model for proforma_invoice.
type ProformaInvoiceModel struct {
}

