// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// ProposeAssignmentsModel is the Terraform model for propose_assignments.
type ProposeAssignmentsModel struct {
}

