// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// PublicReturnsModel is the Terraform model for public_returns.
type PublicReturnsModel struct {
}

