// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// PurchaseOrderModel is the Terraform model for purchase_order.
type PurchaseOrderModel struct {
}

