// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// RecurringTemplateModel is the Terraform model for recurring_template.
type RecurringTemplateModel struct {
}

