// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// ReorderProposalModel is the Terraform model for reorder_proposal.
type ReorderProposalModel struct {
}

