// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// ReplenishmentModel is the Terraform model for replenishment.
type ReplenishmentModel struct {
}

