// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// ReturnOrderModel is the Terraform model for return_order.
type ReturnOrderModel struct {
}

