// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// ServiceAssignmentModel is the Terraform model for service_assignment.
type ServiceAssignmentModel struct {
}

