// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// ShippingThresholdModel is the Terraform model for shipping_threshold.
type ShippingThresholdModel struct {
}

