// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// ShippingRuleModel is the Terraform model for shipping_rule.
type ShippingRuleModel struct {
}

