// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// SilentPartnerModel is the Terraform model for silent_partner.
type SilentPartnerModel struct {
}

