// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// StockTransferModel is the Terraform model for stock_transfer.
type StockTransferModel struct {
}

