// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// StockMovementModel is the Terraform model for stock_movement.
type StockMovementModel struct {
}

