// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// SupplierInvoiceModel is the Terraform model for supplier_invoice.
type SupplierInvoiceModel struct {
}

