// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// SupplierConditionModel is the Terraform model for supplier_condition.
type SupplierConditionModel struct {
}

