// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// SupportTicketModel is the Terraform model for support_ticket.
type SupportTicketModel struct {
}

