// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// TicketMessageModel is the Terraform model for ticket_message.
type TicketMessageModel struct {
}

