// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// TimeEntriesModel is the Terraform model for time_entries.
type TimeEntriesModel struct {
}

