// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// TrainingAssignmentModel is the Terraform model for training_assignment.
type TrainingAssignmentModel struct {
}

