// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// UserManagementModel is the Terraform model for user_management.
type UserManagementModel struct {
}

