// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider


// WarehouseStockModel is the Terraform model for warehouse_stock.
type WarehouseStockModel struct {
}

